### ISSUE TITLE
Summary of Typescript bug

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/overmind#123]
Okay, so we had an issue with Typescript. It seems that the following behaves differently in Typescript:

**Works**
```ts
import * as actions from "./actions"
import * as state from "./state"

export { actions, state }
```

**Works**
```ts
import * as actionsA from "./actionsA"
import * as actionsB from "./actionsB"
import * as state from "./state"

const actions = Object.assign({}, actionsA, actionsB)

export { actions, state }
```

**Does NOT work**
```ts
import * as actionsA from "./actionsA"
import * as actionsB from "./actionsB"
import * as state from "./state"

const actions = { ...actionsA, ...actionsB }

export { actions, state }
```

**Does NOT work**
```ts
import { someAction } from "./actions"
import * as state from "./state"

const actions = { someAction }

export { actions, state }
```

To me it seems that creating a new object here breaks the typing. As if the `import * as something` is not really a traditional object, it is an "exports object". If you start breaking that object apart the typing gets lost. The weird thing is that `Object.assign` still works, but that could because of its explicit typing.

Anyways... this is the issue and if someone wants to throw their thoughts on this maybe we could create a Typescript bug issue.

**Comment by garth** [comment]
But the thing I can't explain is that the last example did work in an earlier version of overmind..., so although this appears to be a TS bug, some change in the latest version of overmind has triggered it.

**Comment by gaspard** [comment]
Is it possible to create a self-contained project with the bug ? We could then see what changes in overmind types might prevent this. It would also be something important if you submit this bug...

**Comment by christianalfoni** [comment]
Closing old issue
