### ISSUE TITLE
multiple trackings on same component does not work

### ISSUE THREAD

**Issue by fopsdev** [cerebral/overmind#129]
hi there

i have some custom-elments tracking state changes.
but the render() implementation is not at a single point.
this means that in my case there get some additional rendering called after the main render.
(i'm using lit-html and there is a repeat directive and which gets executed after the main rendering)
so i have to track those as well.
now i've discovered that a subsequent start and end-tracking on a component followed by a mutationlistener.update will result in loosing the paths from the first tracking

https://codesandbox.io/s/1ym754x404

any help appreciated

**Comment by FWeinb** [comment]
You need to `clearTrackState` in the reverse order you started tracking it. So in your `doRender()` try this:
```js
function doRender() {
  let trackId = trackState()
  let field1 = app.state.Sort.Field1

  // start another tracking... (remove it and it will work)
  let trackId2 = trackState()
  let field2 = app.state.Sort.Field2
  let paths2 = clearTrackState(trackId2)
  let paths = clearTrackState(trackId) 
}
```

**Comment by fopsdev** [comment]
thanks...but its a bit more complex because the second render may happen or not and i don't have direct control over it

**Comment by fopsdev** [comment]
thats the failing testcase if it helps:
```js
test('listener should be called after updating paths', () => {
  const tree = new ProxyStateTree({
    foo: 'bar',
    bar: 'baz',
  })
  const state = tree.get()
  let updateCount = 0
  // access foo and track it
  let trackId = tree.startPathsTracking()
  state.foo
  let paths = tree.clearPathsTracking(trackId)
  const listener = tree.addFlushListener(paths, () => {
    updateCount++
  })
  // access bar and track it
  trackId = tree.startPathsTracking()
  state.bar
  paths = tree.clearPathsTracking(trackId)
  listener.update(paths)
  // mutating foo should call listener
  tree.startMutationTracking()
  state.foo = 'bar2'
  tree.clearMutationTracking()
  tree.flush()
  expect(updateCount).toBe(1)
})
```

**Comment by FWeinb** [comment]
I don't think the test case should pass. 
You are explicitly calling `clearPathsTracking` after accessing `state.foo` and therefore these paths are cleared and should not leak into the next `clearPathsTracking`.
 
`startPathsTracking`/`clearPathsTracking` should be called before and after each render cycle is done. This allows do differentiate the various nested render calls and don't leak path tracking to a parent.

**Comment by fopsdev** [comment]
hmm yes, i did something wrong as it looks like.
after reverting everything back to regular "nested" - tracking it works as expected :)
i think i went down the wrong route after i've recognised that a property wasn't tracked but it was accessed. now its still not tracked and i need to elaborate on that.
thanks for pushing me into the right direction :)
