### ISSUE TITLE
wait/debounce do not behave as expected

### ISSUE THREAD

**Issue by claytonsurgeon** [cerebral/overmind#139]
when running a pipe like:

pipe(
  debounce (1000),
  mutation(funtion1),
  wait(1000),
  mutation(function2)
)
**expected:**
...1 second later
mutation 1
...1 second later
mutation 2

**current behavior:**
...1 second later
...1 second later (for total of 2 seconds)
mutation 1
mutation 2

**Comment by christianalfoni** [comment]
I believe this is old issue, but please let me know if it still happens. Very sure this is solved
