### ISSUE TITLE
Safari can only view documentation landing page

### ISSUE THREAD

**Issue by gitnix** [cerebral/overmind#187]
Can only view the home screen of (https://www.overmindjs.org/) with Safari Version 12.0 (14606.1.36.1.9)
Getting `Unhandled Promise Rejection: SecurityError: The operation is insecure.` when trying to navigate to other sections.
<img width="491" alt="screen shot 2019-01-14 at 7 30 00 pm" src="https://user-images.githubusercontent.com/5448785/51150115-efac7900-1832-11e9-9e23-be657184e5aa.png">

**Comment by edgesoft** [comment]
@gitnix It works for me in Safari Version 12.0.3. Can we close this? Can not replicate.

**Comment by gitnix** [comment]
Yes. It is working for me. Closing.
