### ISSUE TITLE
Unsure of the meaning of some code in docs

### ISSUE THREAD

**Issue by possibilities** [cerebral/overmind#196]
Hi, flipping through the docs I was unsure what the meaning of these lines of this example is. Could it be omitted?

https://github.com/cerebral/overmind/blob/61a2c82981410a71cd15b297ec8b7ff4440f55d2/packages/overmind-website/examples/guide/writingtests/effect.ts#L65-L68

**Comment by edgesoft** [comment]
@possibilities It could be omitted. It is just an example on how to make an Api where you pass an axios instance and pass additional parameters that you might use in the Api.

**Comment by christianalfoni** [comment]
Yeah, let me more explicit in the docs on that issue :) Thanks for feedback! Doc feedback is super valuable! Will be part of next release
