### ISSUE TITLE
Module class

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/overmind#2]
```js
import Overmind from 'overmind'

const app = new Overmind({
  reactions: {},
  state: {},
  actions: {},
  catch: [],
  modules: {}
})
```

The first argument to the main class constructor is the "main module definition". This definition is passed into a Module class:

```js
class Module {
  constructor (moduleDefinition) {}
}
```

The Module class is responsible for traversing the definition and do the following conversions:

1. Make **actions** runable by wrapping them in a function which uses the **runAction** method
2. Replace sub module definitions with Module classes receiving those definitions

**Comment by christianalfoni** [comment]
Not what we are going to do :)

**Comment by aislanmaia** [comment]
This mean is not possible to define our modules like classes?

**Comment by christianalfoni** [comment]
@aislanmaia 

Ah, yeah, no... it does not really make sense to use classes. The reason being that it would basically just looks like:

```js
class MyModule extends Module {
  reactions = {}
  state = {}
  actions = {}
  // ...
}
```

Just a lot of additional syntax with literarily no added value 😄
