### ISSUE TITLE
Async actions don't return a proper promise

### ISSUE THREAD

**Issue by luisherranz** [cerebral/overmind#206]
I'm wondering why async actions don't return a proper promise:
```js
actions: {
    waitFor3sec: async () => {
      await new Promise(resolve => setTimeout(resolve, 3000));
      return "done";
    }
  }

// ...
console.log("now");
await overmind.actions.waitFor3sec(); // <- this seems to be sync
console.log("after 3 seconds");
```
Complete example here: https://codesandbox.io/s/6loqylpk3k

They also don't seem to return the returned value (`'done'` in this case).

We are currently using MobxStateTree but thinking about moving to Overmind.

**Comment by JM-Mendez** [comment]
@luisherranz I think I can help...

I'm just learning overmind atm, so I could be wrong about this. But it seems that this library follows the flux architecture, and as such doesn't return anything from an action. 

You can test it by making the following changes. You'll see it still returns a promise (in the video guide I believe he mentions that actions are async to allow batching, e.g like `setState` in react)

```js
actions: {
    // do not make async
    waitFor3sec: () => { }
  }

console.log("now");
// do not use await or else the promise behaves as if it was sync
const promised = overmind.actions.waitFor3sec();
console.log("after 3 seconds");
console.log(promised); // Promise {<pending>}
```

**Comment by luisherranz** [comment]
Yeah, I saw it returned a promise. For that reason the title is *Async actions don't return a **proper** promise* instead of *Async actions don't return a promise* 😅 

Our use case for these promises is even before we start React. We use them for an initialization hook called `beforeServerSideRendering` which is similar to `getInitialProps` from Next. This is our SSR workflow:
1. Start MobxStateTree and populate its state with the url (we also use a state first routing).
2. Launch all the `beforeServerSideRendering` actions for each package (it may be for each domain). Each one does different stuff, but mostly they fetch the data React needs for that url.
3. Once all `beforeServerSideRendering` actions have finished and state is properly populated do server's `ReactDom.render`.
4. Send both the HTML and the state snapshot to the client.
5. Start MobxStateTree again, this time using the snapshot received from the server.
6. Start React in the client with `ReactDom.hydrate`.

We find this workflow very convinient, really. If we move to Overmind we would like to preserve it. Actually, we used to do it with Redux Sagas back in those days.

**Comment by JM-Mendez** [comment]
> Yeah, I saw it returned a promise. For that reason the title is _Async actions don't return a **proper** promise_ instead of _Async actions don't return a promise_

Sorry then I still don't follow. My impression was that you expected the action to `return "done";`, but it's my understanding that not even redux saga actions return anything to the caller. 

And from a cursory glance at the codebase, it looks like overmind provides a mutable copy of the state to the action's scope and forwarding the result of any changes.

> Our use case for these promises is even before we start React. We use them for an initialization hook called `beforeServerSideRendering` which is similar to `getInitialProps` from Next. This is our SSR workflow:

I think you should be able to use `onInitialize` in the server to set the state, then use it to rehydrate your state in the client. This would work similarly to redux.

**Comment by luisherranz** [comment]
> Sorry then I still don't follow. My impression was that you expected the action to `return "done";`

Yes, but as you discovered, the action returns a promise: `console.log(promised);` but it's not the real promise because you can't await for it.

```js
console.log("now");
const promised = overmind.actions.waitFor3sec();
console.log(promised); // Promise {<pending>}
await promised; // <- it should stop 3 seconds here, but it doesn't.
console.log("after 3 seconds");
```

> it's my understanding that not even redux saga actions return anything to the caller.

Yes, you can start the saga with `runSaga`, with `toPromise()` and wait until it finishes:
```js
// ↑ start Redux
const saga = sagaMiddleware.runSaga(beforeServerSideRenderingSaga);
await saga.toPromise(); // wait until they finish.
// ↓ render React
```
https://redux-saga.js.org/docs/api/#task

> I think you should be able to use `onInitialize` in the server to set the state, then use it to rehydrate your state in the client.

I see in the example that `onInitialize` may be async, but `new Overmind` isn't. So I wonder where does it awaits, if it does:
https://overmindjs.org/api/onInitialize?view=react&typescript=false

```js
const onInitialize = async ({ state, effects }) => {
  const initialData = await effects.api.getInitialData()
  state.initialData = initialData
}

const overmind = new Overmind({ onInitialize, state, actions })

// no await??

ReactDom.render(<App overmind={overmind} />, document...)
```

**Comment by luisherranz** [comment]
Yes, `app.initialized` exists and it returns a pending promise, but I still can't make it wait for initialization:
https://codesandbox.io/s/xopo5mozw

```js
  const overmind = new Overmind({
    onInitialize: async () => {
      await new Promise(resolve => setTimeout(resolve, 3000));
    },
    state: {
      name: 'John'
    }
  });

  console.log('now');
  console.log(overmind.initialized);  // Promise {<pending>}
  await overmind.initialized; // Doesn't stop 3 seconds
  console.log('after 3 seconds');
```

I'm not sure what these pending promises from actions or this one are, but they are not the real action/onInitialize promises.

**Comment by luisherranz** [comment]
> `runSaga` allows running sagas _**outside**_ of redux

That's not entirely true. You can start them outside of redux (with `runSaga`) but if you dispatch actions you will modify redux's state.

Anyway, I hope there's a way to do this with Overmind!

**Comment by JM-Mendez** [comment]
I found the bug. I've only been reading this codebase for a couple of days, but it seems like the `onInitialize` method was being queued internally with the other actions. I'm not sure how it decides to flush the queue tho. And obviously we'd like it to finish initialization first.

I was able to fix it, but again, I'm not sure how the library is architected, so it might break something not covered in the tests (they all pass). Although the changes are extremely minor.

You can compare changes [at my fork](https://github.com/cerebral/overmind/compare/next...JM-Mendez:fix-onInitialize?expand=1)

I put up a codesandbox for you to try out. I had to build and separate the overmind module and install from github in `package.json` to grab the changes.

https://codesandbox.io/s/zqjopp0lk3

If you find it works, then I can ask what their PR procedure is.

Not sure if you (or anyone else reading this) knows about `patch-package`, but you can use that to make my changes locally in your `node_modules` in the meantime. 

Or you can pull it from [my packaged overmind module](https://github.com/JM-Mendez/overmind-dist-fork)

Hope that helps!

**Comment by JM-Mendez** [comment]
> That's not entirely true. You can start them outside of redux (with `runSaga`) but if you dispatch actions you will modify redux's state.

This is good to know! I thought they were orthogonal.

**Comment by christianalfoni** [comment]
Hi guys! :)

That the returned promise form an action is not "awaitable" must be a bug. Thanks for the suggested fix @JM-Mendez! I will look into that and make it fit nicely in :-) 

The reason actions does not return a value is really to avoid patterns where you decouple your logic into multiple actions. When you get into the need of composing logic we encourage you to look at the functional API. That will allow you to run actions in order, map in new values etc. https://www.overmindjs.org/guides/intermediate/04_goingfunctional?view=react&typescript=false

An additional benefit here is that Overmind will also understand what is "coherent" logic, allowing you to debug it better, as seen in this devtools video: https://www.overmindjs.org/videos/devtools-introduction?view=react&typescript=false

But guys, this is awesome, thanks so much for discussing and sharing. Stay tuned for bug fix :)

**Comment by christianalfoni** [comment]
Okay, I identified the issue, pushing fix, will be part of next release. Thanks again for investigating and helping out :)

**Comment by luisherranz** [comment]
> I found the bug. I've only been reading this codebase for a couple of days,

@JM-Mendez wow, amazing. Thanks for the fix and the codesandbox!

I started studying `proxy-state-tree` yesterday, and I'm going to learn TS to be able to understand the library and contribute myself as well.

> Okay, I identified the issue, pushing fix, will be part of next release. Thanks again for investigating and helping out :)

@christianalfoni thanks for chiming in. I'm glad you will allow awaiting actions in Overmind :)

**Comment by christianalfoni** [comment]
Everything should be good in `next` now, if you want to test:

```
npm install overmind@next overmind-react@next
```

for example :)

Please reopen if still issue. Official release should be this Friday.

**Comment by luisherranz** [comment]
Working perfectly now in `@next`: https://codesandbox.io/s/r073jp1jl4

Both actions and onInitialize :)
