### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by luisherranz** [cerebral/overmind#207]
Any intention to add middleware support? 😄

**Comment by edgesoft** [comment]
@luisherranz Can you specify more on what you want to achieve?  Think Overmind already have the ability to make this happen.

**Comment by luisherranz** [comment]
Sure. 

Maybe something like this for mutations:
```js
addMutationMiddleware(({ mutation, next, abort }) => {
  if (mutation.path === 'state.xxx' && mutation.value === 'aaa' ) {
    abort() // abort the mutation 
  } else if (mutation.path === 'state.xxx' && mutation.value === 'bbb' )
    mutation.value = 'ccc' // change the value of the mutation
    next(); // and keep executing other middlewares
  } else {
    next(); // do nothing, but keep executing other middlewares
})
```

And something like this for actions:
```js
addActionMiddleware(({ action, next, abort }) => {
  if (action.path === 'actions.someAction' && action.args === 'aaa' ) {
    abort() // abort the action 
  } else if (action.path === 'actions.someAction' && action.args === 'bbb' )
    action.args = 'ccc' // change the action args
    next(); // and keep executing other middlewares
  } else {
    next(); // do nothing, but keep executing other middlewares
})
```

**Comment by christianalfoni** [comment]
@luisherranz 

Thanks for suggesting features! :)

It is certainly an interesting idea, but the Overmind API is locked for now. We have to do this to bring our current plans to life and at the same time make sure we have a stable codebase.

What would help here, further down the road, is concrete examples of existing scenarios you think would be solved with this feature. Adding APIs has quite a big cost and we want to make sure that we are solving real scenarios that is impossible to solve with current API :)

Hope I was not discouraging here, really appreciate suggestions!

Please reopen if you want to discuss and iterate it more :)

**Comment by luisherranz** [comment]
Sure Christian! Middleware support is the ultimate extensibility tool for libraries like Overmind.

Bear in mind that middleware tools are not for beginners, but for advanced users. It shouldn't complicate the "user" API, and it should not be explained in the "Learn Overmind" tutorials so it shouldn't affect how simple Overmind is.

To get a grasp of what can be done with middleware you can take a look at some of the Redux packages: https://github.com/xgrommx/awesome-redux#react---a-javascript-library-for-building-user-interfaces

You may think that many Redux middleware packages are not needed in Overmind because many things are already addressed by Overmind itself, but the best thing about giving tools to the community is that you never know what they will come up with :)

By the way, MobxStateTree also has middleware support with some interesting packages:
https://github.com/mobxjs/mobx-state-tree/tree/master/packages/mst-middlewares

Both Redux and MobxStateTree implement some "official features" using its own middelware API: [`reselect`](https://github.com/reduxjs/reselect), [`redux-thunk`](https://github.com/reduxjs/redux-thunk) or [`onAction`](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/middlewares/on-action.ts). In Overmind, for example, the official overmind-devtools could use the middleware API. Not that is crucial, but I think it's a good pattern to follow.

> It is certainly an interesting idea, but the Overmind API is locked for now. We have to do this to bring our current plans to life and at the same time make sure we have a stable codebase.

Sure. Let's leave it for now. No problem as this is a tool for advanced users :)

**Comment by mikecann** [comment]
I know this issue is closed but I too would like Middleware. I am currently using MobXStateTree because of the support for middleware. 

The usecase is chrome extensions. You want to have a single state object in your background page, then in your child pages you want to intercept actions and send them to the background. Visa-versa you want to send state changes from your background pages back to your child pages. 

There is a popular Redux middleware library that does this too which I hope will demonstrate better than my description: https://github.com/tshaddix/webext-redux
