### ISSUE TITLE
parallel operator crashes in production build

### ISSUE THREAD

**Issue by fintara** [cerebral/overmind#210]
Hi,

I use `parallel` to load two resources at the same time - works fine in dev. When I run the dist files, I get "Cannot read property 'concat' of undefined", which points here:

https://github.com/cerebral/overmind/blob/b2e282b30c1e32990c4fe3dd39e282490ebc00a0/packages/node_modules/overmind/src/index.ts#L907

```typescript
export const loadFirst: Action = async ({ state, effects }) => {
  state.first = await effects.api.getFirst()
}

export const loadSecond: Action = async ({ state, effects }) => {
  state.second = await effects.api.getSecond()
}

export const loadAll: Operator = parallel(
  action(loadFirst),
  action(loadSecond)
)
```

I'm using it in a React project created with create-react-app.

**Comment by christianalfoni** [comment]
Thanks a bunch, it is merged! :)
