### ISSUE TITLE
Support for React Concurrency/Hooks

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#211]
As I understand, React is going with a pull rather than push based model. I could imagine overmind working with that by (in the abstract) storing the "previous" or current value in a cache until the next update propagates.

Just wanted to open the ticket here so there's a googleable discussion: would this be possible and coherent with Concurrent mode? Is it supported yet?

**Comment by christianalfoni** [comment]
It depends on how Concurrent mode works. As I understand it just intercepts the rendering "between components", sometimes throwing pending rendering as there is new rendering to be done instead. But if a component renders, the "render" method or the function body will run synchronously... cause well, it has to. And that is where the tracking occurs. We do not care about when components render, as long as the function/render method runs synchronously... and they have to, cause that is JavaScript :)

**Comment by christianalfoni** [comment]
With the new Angular update there is a 3rd tracking strategy introduced which gives each component its own tracking tree and proxies. That means rendering could happen anywhere, between, in between components etc... would not matter, whatever is exposed inside the component is tracked to that component. So we have a backup on that :)

**Comment by christianalfoni** [comment]
Closing this for now as I am very confident that we will not get into any issues here, but please reopen if this is tested and odd things happen :)
