### ISSUE TITLE
Breaking changes before official release

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/overmind#222]
After the announcement we have gotten a lot more people testing out Overmind. Especially the Vue and Angular (coming soon) views has gotten some amazing updates. But also smaller details on the API can be improved. In this issue we will list the breaking changes we want to make before the official release:

### 1. Separate value from configuration

In actions you receive:

```js
const myAction = ({ state, effects, actions, value })  => {

}
```

This `value` does not really belong in the rest which is defined as "the configuration" of the app, it maps directly to the configuration. So we want to separate that out:

```js
const myAction = ({ state, effects, action }, value)  => {

}
```

This is more intuitive, as you can think of the first argument as "the context" of the action, pointing to the Overmind instance.

#### Amount of work
- Refactor devtools
- Refactor website
- Rewrite all documentation (there are a lot of examples)
- The VueX video is wrong... though we can maybe add a note to it instead. I have not figured out how to add like "notes"... maybe we can use this link notifier and say: "API CHANGE" and link to the documentation... yeah, that could work

**Comment by gaspard** [comment]
I have some more details on this proposition here, also trying to bind `this` as context #223.

To help migrating existing apps, it could be easy to deprecate old API by checking `action.length` and not just blowing things up.

**Comment by FWeinb** [comment]
Doing the `actions.length` check and issuing is a great idea! 
I would suggest adding warning that using `value` is deprecated if a value property was detected in the context.

**Comment by gaspard** [comment]
Bind **this** as context in actions and effects: #226

This is just a small addition to #225 (separate value) but it further helps by removing the context from the arguments completely and lets the user focus on the values and function calls.

**Comment by Spiralis** [comment]
While writing my app one of the most unintuitive things was adding the arguments to the one context object. 
With this suggestion, are we also opening for an arbitrary number of values? 
I think that is what most devs intuitively would want to try. And, each value would require no additional typing as each param is a built-in datatype (in most cases at least) .

**Comment by eirikhm** [comment]
> With this suggestion, are we also opening for an arbitrary number of values?

That would be great!

**Comment by gaspard** [comment]
The problem with any number of arguments is with `TOperator` typing. I also think that argument through position is not that intuitive unless it is regular and exists for a good reason (like having context, value).

```html
<!-- I am not sure this is any better... -->
<span onClick={() => actions.setOnFire(me, mySexyFriend)}>...</span>
<!-- ...then this -->
<span onClick={() => actions.setOnFire({user: me, friend: mySexyFriend})}>...</span>
```

**Comment by gaspard** [comment]
We should change signature for **Derive** as well to:

```ts
// Derive should access `effects` as well and order of arguments should be
// Context, Parent so that it is similar to actions and effects and components.
export type IDerive<ThisConfig extends Configuration, Parent extends TStateObject, Value> = (context: IContext<ThisConfig>, parent: ResolveState<Parent>) => Value;
```

**Amount of work**
* refactor apps (small number of derive probably)
* fix examples (small also)

**Comment by christianalfoni** [comment]
1. About the multiple arguments to actions: It did cross my mind, but quickly left it, because I think the typing will be problematic. But what @gaspard brings up here is way more important. Operators only have one value, so we have to stick with it

2. @gaspard I do not agree that derived should be passed a config. It is "Derived State". If we mix in effects and action all sorts of havoc could happen. Derived is just a "complex state definition", it does not have anything to do with the other concepts of Overmind. I guess you would want effects to have "helper functions", but the only thing these helper functions could ever do is take some data input and produce a new output, which means they are not really effects. They can safely be imported and used directly

Thanks a bunch for contributing here! :)

**Comment by gaspard** [comment]
@christianalfoni In my way of working, `effects` in actions have the same role as `effects` in component: sometimes have side effects and sometimes simply compute state. In this regard, having them everywhere is a simple way to import helpers without worrying about paths. It also focusses on specific helper functions.

Like now, I have `@lucidogen/data` which exports many types, functions and stuff and it helps having just a small group of things related to state  in `effects`. Not having these helpers in `Derive` when I have them in components feels weird and forces me to export them as raw functions. Not sure it helps.

**Comment by gaspard** [comment]
Either way, we should make the order of arguments similar to what we have in actions:

```ts
type DerivedFunction<Config, Parent, Value> = (context: IContext<Config>, parent: ResolveState<Parent>) => Value
```

**Comment by christianalfoni** [comment]
Yeah, I see the perspective, though we are exposing a lot of things you should never use there. Like the other effects which are not these helper functions and actions should never be triggered. We have to document it as: "We expose everything, but never use the actions, never use async effects, never use effects that does anything else than being helper functions for transforming values"... I feel rather strongly about that ;-)

And where you have a pattern of helpers functions exposed on effects, you can just import these helpers functions directly from your effects file and use them safely in the derived :)

**Comment by gaspard** [comment]
I never said we should expose actions. Just the same context we have as argument to actions.

This:

```ts
{ state, effects }
```

@christianalfoni All effects could "safely be imported" from anywhere. The only interesting about effects is that they are tracked in actions, that they are locally available without needing imports and are easy to mock in tests. All these reasons make them interesting in Derive. We could rename `effects` to `helpers` and it would be better because there is really no reason to treat side effects in any special way from other helpers. Having a way to "tune" the context passed everywhere is what this is.

**Comment by christianalfoni** [comment]
I am sorry, I do not agree with this :-/ Maybe the term `helpers` means different things for us?

But first, the argument to actions is: `{ state, effects, actions }`. With all the ierations maybe you missed that we also include actions? Reason is that actions needs to be able to effectively register event listeners etc. Forcing all event listeners to be registered in `onInitialize` is hopeless. Cause you have logic where listeners are added and removed. I have apps now where it would not be possible to only use `onInitialize`. Also it is expected that you can call actions from actions. All solutions have that possibility and it is a good place to start composition of logic. We of course want to encourage the functional approach, but there is nothing wrong with calling an action from an action.

So for me helpers has nothing to do with `effects`. `effects` is conceptually there to separate low level APIs from your application logic. That way actions does not have any code related to `fetch`, `firebase` or whatever 3rd party tool you use. Actions only use application specific APIs like `getPosts`, `listenForNotifications` etc.  I think this is really important.

In my book `helpers` is a term used for functions that takes an input and produces an output. I see that you want to put them on effects for convenience, but you would not have any issues importing them directly to your code... as they are pure. Unlike `effects` which are impure and often async.

What worries me the most is that the driving factor for this seems to be avoiding import statements? Effects is a very specific concept for avoiding cluttering your code and also having a boundary between your actual application logic and impure low level APIs. Helpers are pure data transformation functions. You would not mock these related to testing your application logic? It would be like mocking _.sortBy or _.map. And the same goes for tracking. Would not want to track those kinds of functions?

Also related to tracking it would be extremely difficult to implement a concept of tracking in derived related to the devtools. Cause derived functions are run whenever something accesses a dirty derived. So there is really no place to put it in the devtools... it could be in an action, it could be from a component.

But again... I have a feeling we have different perspectives on what a `helper` is. But what we can not disagree on is that Dervied functions can only run pure functions which can be safely imported. Exposing impure stuff in those functions is not a good.

**Comment by gaspard** [comment]
@christianalfoni what I call helpers are not just pure transformer functions. Some write to state, some read the state in complex ways, some call the remote server, some wrap js libraries.

We need a way to share features and box them. It does not matter if they are "external" or not or if they have side-effects to the localStorage, remote server or the state tree.

Writing to state should not happen in Derive, of course, in the same way that we should not write to state in components but we **need** this boxing feature for tracking (in actions) and to reuse code that reads the state from components and actions and derive.

What I propose is that we drop this idea of "effects" as it has no meaning. Why look at firebase or moment.js differently from reusable parts of an overmind app like state management ? Why force overmind specific code outside of effects just so that they are consistently imported in actions, components and derive ?

Why on earth impose rules on users just because they could do silly things ? Exposing the `context` and letting users augment this important object is simple, easy to understand and wise. Not doing it does not prevent users from doing silly things like calling a helper that alters the state from a derive. If my `getItem` helper does some weird caching, then it will break the Derive and component uses be it an imported function or something that lives in `context`.

**Comment by christianalfoni** [comment]
Okay, good, I understand what you mean by `helpers` now :)

The sub context here for me is that I think we learned a lot from Cerebral. Overmind has been announced after an experimentation/development  phase of over 6 months now. The API is locked. I think we pushed a lot of developers away from Cerebral because of all the changes we were making after the announcement and now we have a bigger responsibility because we have gotten a lot more attention. This makes me extremely defensive on making changes.

That said, even without this defensive default I would still disagree. Derived is a pure function of state. We should not make any changes that makes the derived function impure, which this suggestion does. Import your pure helpers and use them in the derived. There is no need for possibly hundreds of developers to refactor their code because of this. I do not see how this blocks you in any way.

I ❤️ you @gaspard and I feel shitty about working against you when you are inspired, but I do not see how I could ever budge on this. Effects is now a conceptual term in all articles, discussions, documentation, API and videos and I still think it is a really good term that helps developers separate their code in a healthy way. I am sure we would have great discussions on creating a different concept than `effects` earlier on, but this is what almost burned me out with Cerebral. Going back to all articles, docs, APIs and videos... explaining to everyone why we made the changes. I think it is wise of us to acknowledge that the window for these kinds of changes is passed.

I wanted Overmind to be a small API surface with clear concepts which people can build upon. I think we have achieved that and now is the time to help people use what we have built, not make more changes. If you want to use `effects` conceptually different that is perfectly okay, but we do not have the luxury of making radical changes anymore. It is not fair to all the others, making changes has a huge cost... something I feel really bad about in Cerebral.

**Comment by gaspard** [comment]
I agree with you @christianalfoni. I upgraded (and worked) on Cerebral through so many API changes and type changes and then again with Overmind and we really need things to be cool or we will all burn 🔥😂.

I can live with the way Overmind works now and use this `effects` thing as it is, without needing it inside Derive. It just felt weird having a different argument order and types in Derive from the rest but it is not important.

From "baobab" Cerebral, it went from no types, to weird types, to Overmind which is something that is now very easy to understand and use and I am super proud of you and grateful for all the hard work you put into this 🙏. You are my hero !

**Comment by Spiralis** [comment]
> The problem with any number of arguments is with `TOperator` typing. I also think that argument through position is not that intuitive unless it is regular and exists for a good reason (like having context, value).
> 
> ```
> 
> <span onClick={() => actions.setOnFire(me, mySexyFriend)}>...</span>
> 
> <span onClick={() => actions.setOnFire({user: me, friend: mySexyFriend})}>...</span>
> ```

I am with you @christianalfoni on that it needs one because of Operators. Apart from that I think having multiple arguments is a big plus. It is what devs are used to (even though json objects are getting more and more used). The biggest drawback for me is having to create a separate type in the action-definition to wrap the action value. It looks more cludgy and complex than needed imho. 

But, I understand the argument on the operators, so I guess case closed :).

However - super happy to see the context and the value separated.

**Comment by christianalfoni** [comment]
Yeah, good points @Spiralis. Though yeah... alternative would be to pass an array into operators, though that would be more confusing I think :)
