### ISSUE TITLE
Separate value from context in actions

### ISSUE THREAD

**Issue by gaspard** [cerebral/overmind#225]
Now that we have async mutations and effects tracking, I think we can use these new features to compose actions in pure javascript, without arrays or other syntax complications.

In order to improve the experience with this type of composition, I propose to move the `value` outside of the action context because it is different (as it changes) and makes it easier to tweak the value before passing everything to the next function call.

Example:

```ts
export const backspacePress: Operator<CompositionSelectionArgs> = action(
  (ctx, value) => {
    const { editor } = ctx.effects

    // Action composition as pure JS or TypeScript
    editor.ensureComposition(ctx, value.holder)
    const ops = editor.deleteSelection(ctx, value)
    editor.processOps(ctx, ops)
    editor.changed(ctx, value.holder)
  }
)
```

Other example (composition with `operations` from multiple libraries):

```ts
export const createContact: Operator = action((ctx, type) => {
  const { data, dialog } = ctx.effects

  data.createContact(ctx, type)
  data.clearForm(ctx)
  dialog.show(ctx, 'ContactPrint')
})
```

**Comment by christianalfoni** [comment]
This is implemented :) Will be in `next` tomorrow, just have to fix some tests and implement some deprecation stuff
