### ISSUE TITLE
Overmind devtools as chrome extension

### ISSUE THREAD

**Issue by sanohin** [cerebral/overmind#228]
Hi,
do you have any plans on shipping devtools as a chrome app? This would be more user-friendly and everyone would be up to date.

**Comment by fopsdev** [comment]
Hi,
Devtools was a chrome devtools extension back in the earlier cerebral-days.
If i'm not wrong moving it to a standalone electron app was beneficial because of easier release handling and the possibility to use overmind for the devtools as well.

**Comment by Spiralis** [comment]
I am happy with it as it is now. 
I suggest that a Chrome extension, should it be made, is left to the community instead of @christianalfoni having to maintain it.

**Comment by christianalfoni** [comment]
Hi there, please have a look at a previous answer over here : https://github.com/cerebral/overmind/issues/197#issuecomment-460063169 :)
