### ISSUE TITLE
Proposal: rename value to payload

### ISSUE THREAD

**Issue by luisherranz** [cerebral/overmind#229]
I've been following the conversation here https://github.com/cerebral/overmind/issues/222 about the possibility of having an arbitrary number of arguments and it looks like only one argument will be allowed.

In my experience with other libraries, naming that one argument `payload` instead of `value` may give the developer a better understanding of what it is: the action payload.

```js
action((context, payload) => { ... })
```

It's more of a name for the docs because the name itself is not used in the user's code (like `context`) but may be a good moment to think about it now that it's going to be changed anyway. I'm all in with the overmind approach of making everything as simple to understand as possible.

What do you think?

**Comment by eirikhm** [comment]
This will be changed, so you are free to name it whatever you like :-) See #225 

 ```js
export const changeTitle = ({ state }, title) => {
  state.title = title
}
```

**Comment by luisherranz** [comment]
Yeah, it's more of a name for the docs I guess. Not really that important 😅

**Comment by christianalfoni** [comment]
Ah, yeah, I went through all the examples in the docs and gave them more proper names. I guess it is still called `value` some places... but yeah, feel free to PR changes to them :)

**Comment by luisherranz** [comment]
Sure, thanks :)
