### ISSUE TITLE
try/catch in a pipe

### ISSUE THREAD

**Issue by fintara** [cerebral/overmind#230]
I can't seem to find a way to catch exceptions in a pipe.
For example, if I make an HTTP request (in action or map) and it fails, there is no way to catch it and provide an alternative flow.

I think in Cerebral you could pass a map with success/error keys for the two flows. Maybe something similar could be added here as well?

**Comment by christianalfoni** [comment]
Hi @fintara ,

We will implement more operators very soon. The `op-op` spec written for Overmind operators supports error handling as well.

So either:

```js
tryMap(..., {
  resolved:,
  rejected:
})
``

But also:

```js
pipe(
  action(...),
  catchError(...), // only runs if previous operator throws error
  action(...),
)
```

I think we probably need both, cause there are different situations where you might want one over the other. But yes, this is in "the pipe" (no pun intended) :)

**Comment by christianalfoni** [comment]
https://next.overmindjs.org/api/operators?view=react&typescript=false#operators-catcherror

Will be released soon :)

You can also create your own operators now:

https://next.overmindjs.org/guides/pro/02_createcustomoperators?view=react&typescript=false
