### ISSUE TITLE
Differences from Cerebral

### ISSUE THREAD

**Issue by chimon2000** [cerebral/overmind#239]
Wondering what the differences are between overmind and cerebral? Why the new library?

**Comment by christianalfoni** [comment]
Good question @chimon2000 :)

Cerebral started over 3 years ago and it started out as just a simple idea. Through the years the API changed several times. One of the last efforts on Cerebral was Typescript support, but we never really got to where we wanted. At the same time Mobx got widely popular and Proxies became a standard in web browsers, allowing for a different take on API surface.

So Overmind is not a simple idea, it is rather taking all the experience from Cerebral and other frameworks and creating a minimal API surface to do what you need to do. So mutations are performed with the plain JavaScript mutation API and the effects (providers) are just objects, classes or whatever you choose. You do not have to think about how you expose state to components, you just expose everything and whatever you accessed is automatically render optimized. It is also built with Typescript with a focus on having is little typing as possible for the developer. Especially the functional API, if you choose to use it, has really excellent typing support.

Cerebral is still a really great experience if you write plain JavaScript. It has a very simple API with a a lot of composition power. Overmind should be considered if you write Typescript though. You get a lot more out of the box.

So both projects can solve the same issues, but with different approaches. Cerebral is a bit more exotic with its sequences API, where Overmind has less API and concepts to learn and of course has amazeballs Typescript support :)

**Comment by chimon2000** [comment]
I appreciate the context.  Would it be worthwhile to add this information to overmind's website?

**Comment by christianalfoni** [comment]
Yeah, could write like a guide: "Coming from Cerebral" or something?

**Comment by christianalfoni** [comment]
I have this on my list, just cleaning up issues 😄
