### ISSUE TITLE
Offline examples

### ISSUE THREAD

**Issue by chimon2000** [cerebral/overmind#251]
It would be nice to have an example of how to implement redux-offline features using overmind.

**Comment by christianalfoni** [comment]
Hi there!

Yeah, hm... personally I have not worked on a project where offline support is needed. And I would expect the nature of the app would require different approaches to this? Like depending on what kind of endpoint you are using (plain REST api, Firebase, graphql etc.) and also if you do want to allow changing state related to server side stuff and keep a record of it when offline, to perform them when getting online again... maybe with expiration rules etc. Authentication is of course also something to keep in mind here. Your session might be expired when going online again.

Anyways... what I mean to say is that it is a rather complicated subject :)

But could write up something on syncing your state with local storage and create an HTTP effect that tracks offline requests to run them again when the app is online?

Do you have an example app where offline support is typically required?

**Comment by garth** [comment]
I've made quite a few "offline" apps with cerebral and overmind. I normally use couchdb for the data store for offline apps. But it doesn't really change anything in Overmind.
