### ISSUE TITLE
Combining different stores

### ISSUE THREAD

**Issue by sanohin** [cerebral/overmind#257]
Hi, I would like to know if this possible or can be implemented in the future to use different store value in the derived value?

pseudocode:

```js
const users = createOvermind({
  state: {
    1: {
      id: 1,
      name: "alex"
    },
  }
});

const posts = createOvermind({
  state: {
    list: [{ id: 1, authorId: 1, text: "..." }]
  }
});

const postsWithAuthor = combine(users, posts, (_users, _posts) => {
  return _posts.list.map(post => {
    return {
      ...post,
      author: _users[post.authorId]
    };
  });
});
```

**Comment by christianalfoni** [comment]
Hi @sanohin :)

So you basically want to different instances of Overmind to look into each other? :)

I just have to ask first... if two instances of Overmind are so closely related... why do you want to have two different instances? :) 

I would recommend having one instance of Overmind and rather use namespaces to split up the domains of your application: https://www.overmindjs.org/guides/beginner/05_structuringtheapp?view=react&typescript=true.

Multiple instances are really considered different apps :) But please, tell me more about the scenario if you think that having one instance creates issues.

**Comment by sanohin** [comment]
I tried `namespaces` before and they behaved not as I expected I think, but now it works just fine, thank you!

**Comment by christianalfoni** [comment]
Ah, great to hear!  :-)
