### ISSUE TITLE
Example request: Undo/Redo history

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#258]
I saw the new dev tools shows this, just think it would be helpful to see an idea of how you'd implement this.

Being able to choose the granularity of undo/redo would be nice. Ideally by marking a point as a checkpoint.

**Comment by christianalfoni** [comment]
There are many ways to implement undo/redo. I think we often think of it as a general feature, but actually there are levels of complexity and scope which heavily affects the implementation. Maybe you have a little spec of something you want to undo/redo and we can talk about how to solve that specific scenario? It can inspire to solve more complex scenarios as well :)

**Comment by JM-Mendez** [comment]
I'd also like to implement undo/redo. My use case is relatively simple: I'd like to store `state.current`, `state.future`, and `state.previous`. Yet it seems like reference equality is broken, which would increase my memory usage exponentially.

I know that `immer` uses proxies as well and also has the same issue. I'm not familiar with the internals of theirs or your architecture, but `immer` has a way to replay patches which led to the development of [`immer-undo`](https://github.com/aleclarson/immer-undo).

Would this be as simple as I think it is, by say exposing a way to replay patches like in the devtools? Or would I run into the same issue with references?

I love this lib beyond all I've tried, so if it's possible and you want to guide me through a PR, I'd be happy to do it. Really don't want to go back to `immutablejs` and `redux` if I can help it.

**Comment by JM-Mendez** [comment]
Although on further thought, I guess I could use `overmind` with `immutablejs` objects? It sounds like it'll be an anti-pattern tbh.

**Comment by christianalfoni** [comment]
If you need the freedom to undo/redo any state it becomes a bit challenging in regards of optimizations. As that is exactly what immutability handles really well. That said, you can do a very direct approach with an effect:

```ts
// Using an IIFE
export const history = (() => {
  const records = []

  return {
    initialize(appInstance) {
      appInstance.addFlushListener(() => {
        records.push(JSON.stringify(appInstance.state)
      })
      pop(state) {
        const previousState = JSON.parse(records.pop())
        
        Object.assign(state, previousState)
      }
    }
  }
})()
```

So in `onIntialize` hook you:

```ts
export const onInitialize = ({ effects }, appInstance) => {
  effects.history.initialize(appInstance)
}
```

And in some action you want to undo state:

```ts
export const undoState = ({ state, effects }) => {
  effects.history.pop(state)
}
```

Like this approach now creates a copy of the state on any `flush`. You might want to be a lot more specific. But using `stringify/parse` is a perfectly valid approach. Though this will get you in trouble if your state is really big. You might want to pinpoint what state to actually operate on. Also in this approach with `flush` you probably want to limit the number of records :)

Anyways, this would certainly be a start. Like, what immutable libraries does really well is "structural sharing", which helps a lot on memory load. But if your app just wants to undo/redo some specific state 5 changes back, `stringify/parse` is absolutely no problem :)

**Comment by JM-Mendez** [comment]
Thanks for the quick reply. It seems like immutablejs is the right tool for me since I'll need to be able to store upwards of 100 undo states of some heavy objects.

Still, I much prefer Overmind's mental model and functional style, along with the dev experience. So I'll just use both unless you feel I should do otherwise.

**Comment by christianalfoni** [comment]
You can definitely use both :) Though would be interested in knowing how you combine them specifically. I could give you some pointers maybe on how to take advantage off both worlds in an optimal way :) Just reopen if you want to share more!

**Comment by yuyaoiwa-houzz** [comment]
@christianalfoni Hi! I was wondering how you would implement redo/undo with a structure like so:
{
   past: [],
   present: [],
   future: []
}
but only for specific namespaced states?
