### ISSUE TITLE
HMR causing freeze/infinite loop

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#259]
So, not sure what's causing this. I'm basically just testing Overmind in our app, I put together the router and some small state and hooked it into the app.

For some reason at some point, HMR started doing a very heavy infinite loop that will freeze the tab quickly. I added some logpoints and a breakpoint on the HMR condition, you can see the behavior here:

https://v.usetapes.com/BUENSeCBBt

Any ideas what would cause this? It seems to be calling itself somehow at the forceUpdate area and just continuing to do so ever after.

**Comment by natew** [comment]
Looking further into this:

reconfigure calls forceFlush:

![image](https://user-images.githubusercontent.com/12100/57255073-bf6a2f80-7007-11e9-97a4-9f24ff9b4b7d.png)

That calls this callback to rerender components:

![image](https://user-images.githubusercontent.com/12100/57255131-ddd02b00-7007-11e9-94c0-837022dab9c3.png)

Which then causes the component to rerender and track the path again:

![image](https://user-images.githubusercontent.com/12100/57255158-f0e2fb00-7007-11e9-9ce1-adf0ad24bc2a.png)

And then the loop continues with the new pathDependencies, meaning infinite loop:

![image](https://user-images.githubusercontent.com/12100/57255051-b11c1380-7007-11e9-874b-48c6bbcb0270.png)

I'm guessing the fix is something like, before:

```ts
for (let key in this.pathDependencies) 
```

After:

```ts
for (let key in { ...this.pathDependencies })
```

So it only goes over the current pathdependencies before they get updates. Going to test and submit PR if that wokrs.

**Comment by natew** [comment]
Ok so tried this and seems it's not actually in that area. Went down a number of routes but still stuck, may just leave this for a bit and see if anyone else runs into similar, or attempt an isolation.

**Comment by christianalfoni** [comment]
@natew A colleague showed me this issue and it seems to be the React hook. Are you using that? 

In the new version of the docs there is no reference to passing the overmind instance into the hook/connect. You have to use the provider. That fixes the issue.

https://next.overmindjs.org/guides/beginner/06_usingovermindwithreact?view=react&typescript=true#using-overmind-with-react-with-hook

**Comment by geirsagberg** [comment]
Can confirm, following the steps in the linke above fixed the issue for me.

**Comment by natew** [comment]
I'm still getting it, perhaps it's because I'm co-locating things?:

**om.ts**
```ts
import { createOvermind, IConfig, Overmind } from 'overmind'
import { createHook } from 'overmind-react'
import { merge, namespaced } from 'overmind/config'

import * as actions from './actions'
import * as apps from './apps'
import * as effects from './effects'
import { onInitialize } from './onInitialize'
import * as router from './router'
import * as setupApp from './setupApp'
import * as spaces from './spaces'
import { state } from './state'
import * as user from './user'

const config = merge(
  {
    onInitialize,
    state,
    actions,
    effects,
  },
  namespaced({
    router,
    setupApp,
    apps,
    spaces,
    user,
  }),
)

export type Om = Overmind<typeof config>

export const om: Overmind<typeof config> = createOvermind(config, {
  logProxies: true,
})

export const useOm = createHook<typeof config>()

window['om'] = om

declare module 'overmind' {
  interface Config extends IConfig<typeof config> {}
}
```

**index.tsx**
```
import { om } from './om'
ReactDOM.render(<Provider value={om}><div /></Provider>)
```

When I hit save I hit an infinite loop that freezes the tab immediately.

**Comment by christianalfoni** [comment]
@natew Yeah, you have to instantiate overmind in the same file you render out the app :) It really is a good thing to separate the config and the instantiation as that is also needed for testing and ssr. And it should also fix hot reloading :)

The docs should reflect this now, but yeah, we did it this way initially :)

**Comment by natew** [comment]
I tried both actually and found it still freezing. I’ll try and come up
with a reproduction today, any idea why that may still happen?

**Comment by christianalfoni** [comment]
Hm, that is weird. I am not sure why it froze in the first place actually. Would have to dive more into it, but I would try to just comment out a lot of the app close to the render. Only having one component using the hook for example. Maybe it is related to accessing something, hm. But yeah, been using it a lot myself and it should just work :)

**Comment by natew** [comment]
I still get this (just tried it again to see). Would you be interested in joining our private repo and taking a look? Everything should bootstrap fairly standard so you can test, happy to pay a consulting fee as well.

**Comment by natew** [comment]
If it's of any help, I basically see this just calling over and over:

![image](https://user-images.githubusercontent.com/12100/60990145-995d5600-a2fc-11e9-99e7-bc5692c39452.png)

**Comment by christianalfoni** [comment]
@natew Yeah, for sure, I can jump on and see what is happening here :)

**Comment by natew** [comment]
Started a whole new project, didn't copy anything over, and somehow still ran into this! But it is only triggered by some files, so I'm checking into it agian.

**Comment by christianalfoni** [comment]
I have a feeling this is related to the setup then @natew . Is your new project smaller? Something you could share or easily reproduce with shareable code? 😄
