### ISSUE TITLE
Make `derive` a special kind of proxy to not resolve all functions

### ISSUE THREAD

**Issue by gaspard** [cerebral/overmind#265]
The gist of the idea is to change `dynamic values` resolution from resolving all functions to using a dedicated wrapper.

This is a breaking change but it fixes the most annoying and illogical feature of overmind. This feature has a big impact on many parts of Overmind without the added value being enough of a justification for this in my view.

## Pros

So first I'll start with the nice value of this `functions are called on get`. Creating a derived value is elegant and simple: simply insert a function in the state tree. Getting the value back is like getting any other value, without any extra work.

## Cons

My biggest grudge against this is that it breaks one of the most intuitive aspects of a state tree: read & write consistency. This "feature" breaks types and intuition all the time:

```ts
// Config definition, here `sortedKeys` is a function.
interface MyState {
  sortedKeys: (...) => {...} // derived value
  data: ...
}

// In the context, here `sortedKeys` is an array of strings:
ctx.state.sortedKeys

// When writing to state, if you change the sorted functions, you have to do:
ctx.state.sortedKeys = (...) => {....}
// and when you read value back
const func = ctx.state.sortedKeys
// you get... the result of the executed function. Totally unintuitive and dangerously messy
```

In some earlier version of Overmind, only the functions set on initial state definition would behave like this and at least, it made the `write/read` in the app consistent. But now, this is really not cool at all because you are forced to break your own types to change a function or are forced to wrap the function in a function to avoid execution on read.

This has multiple consequences:

1. write / read in the state is inconsitent
1. it is easy to put a function in the state and have weird bugs with the function being executed in surprising ways
1. types resolution (ResolveState) is unnecessarily complicated
1. it makes storing components or other "complicated values" behind functions ugly

And finally, the most important fact:

1. It is super easy to fix all these annoying problems by simply wrapping the derived state in a derive function that simply attaches a symbol to the passed function: IS_DERIVE.

```ts
ctx.state.sortedKeys = derive((...) => {...}) // this is the only required change: use the `derive` function on write. We can even trick TS into thinking we are writing and array of strings if we want so that this operation is type safe and consistent.
```

Concerning implementation, we simply check `someFunc[IS_DERIVE]` before executing the function on `get`. We can use a simple trick to resolve state type based on using the `Derive<T>` thing.

Or (**my favorite solution**) just remove everything related to derive and simply let people use effects:

```ts
// Using effects
const sortedKeys = ctx.effects.sortedKeys(data)

// Or using any function
const sortedKeys = sortKeys(data)
```

Since `derive` is not cached and does not have anything special about it, the solution above works just fine and removes quite some complexity in the whole `state` handling thing.

**Comment by christianalfoni** [comment]
There are many things I would like to have done differently with Overmind, learning from the experience of creating it. We decided that functions in the state tree are considered "derived functions" which certainly has its pros and cons... cons we did not know until after release as well. But I do not want to go full circle on that decision now as it has a high cost. First have to evaluate the change, all docs needs to be updated, videos are wrong, all developers on existing projects needs to refactor, refactor codebase, write tests etc. It is just an insane amount of work.

I am really sorry, but I have to be really stubborn about this and consider it a "lesson learned". We could rather open up an option that allows you to turn off derived functions:

```ts
createOvermind(config, {
  derivedFunctions: false
})
```

The `derived` functionality is specific to Overmind, not proxy-state-tree. So yeah, can just turn it off and you can go with your ideal approach :)

**Comment by gaspard** [comment]
OK, I was thinking on something like this, having an **opt-out** would be really cool. We would also need a way to not resolve functions in types (I am thinking `ResolveState`).

You are right, it's a lesson learned. When this thing came up, it looked so elegant and "perfect". It's actually an interesting example for me of perfection gone awry 😅.

Since I'm the one in need of an "opt-out", let me know if you want me to do a PR...

**Comment by christianalfoni** [comment]
Yeah, exactly :) "beautiful" is often "impractical" :D

Ah, yeah... would love a PR on this. Good point with `ResolveState`, not quite sure how to solve that one. Maybe you have an idea? Maybe pass something to `IConfig` on how to evaluate or something...

**Comment by christianalfoni** [comment]
I will just close this to clean up, please reopen to discuss more on how to approach this. Still not sure on how to fix the typing there, hm hm
