### ISSUE TITLE
Unhandled Rejection (TypeError): Converting circular structure to JSON

### ISSUE THREAD

**Issue by louisgv** [cerebral/overmind#267]
I was trying to set state in an action. The object I'm putting into state does have function in it, so I assume that's the problem with circular structure. Why does the state not allow circular structure?

Also the error was thrown by the overmindjs devtool. 

The project was created using `create-react-app`

![image](https://user-images.githubusercontent.com/6723574/58221022-e8581900-7cc5-11e9-96ab-d67649574ca1.png)

**Comment by christianalfoni** [comment]
Hi @louisgv !

Wow... this is a late response.

I believe we protect against circular structures now and there are plans to create a custom serializer for the devtools, which would also handle this. But out of the box serializers break on circular data.
