### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by hrnik** [cerebral/overmind#268]
Hello, want to ask about WebSocket support. Have this example of code, and basically, it's work.
But the question, do we have some "right" way to work with WebSocket?

If we subscribe to _onmessage_ in action it's ok?

```js
import { Overmind } from "overmind";
import { createHook } from "overmind-react";

export const api = (() => {
  let socket;

  return {
    initialize() {
      socket = new WebSocket("wss://echo.websocket.org");
    },

    getSocket() {
      return socket;
    }
  };
})();

const overmind = new Overmind({
  onInitialize: ({ effects }) => {
    effects.initialize();
  },
  state: {
    message: ""
  },
  actions: {
    initWS: ({ state, effects }) => {
      effects.getSocket().onmessage = function(event) {
        state.message = event.data;
      };
    },
    sendMessage: ({ state, effects }, message) =>
      effects.getSocket().send(message)
  },
  effects: api
});

export const useOvermind = createHook(overmind);

```

**Comment by corlaez** [comment]
You are wrapping the api in an effect. That looks good since the socket is an api that communicates with the outside world.
And since you already said the thing seems to be working. This looks good.

However I would write it a little different to ease testing.
initWS seems a little hard to mock because we use getSocket(). Instead I would expose something like setOnMessage(callback)
```js
    initWS: ({ state, effects }) => {
      effects.setOnMessage(function(event) {
        state.message = event.data;
      });
    },
```
And that in my eyes could be mocked with less friction.

**Comment by christianalfoni** [comment]
Insanely late answer and sorry for that:

```js
const overmind = new Overmind({
  onInitialize: ({ effects }) => {
    effects.initialize();
  },
  state: {
    message: ""
  },
  actions: {
    initWS: ({ state, effects, actions }) => {
      effects.getSocket().onmessage = actions.setMessage;
    },
    sendMessage: ({ state, effects }, message) =>
      effects.getSocket().send(message)
  },
  setMessage: ({ state }, message) => {
    state.message = message
  },
  effects: api
});
```

This is how you would do it. But would suggest using `onInitialize` to initialize your websocket connection and pass in the action to react on messages 😄
