### ISSUE TITLE
Documentation overmind-devtools

### ISSUE THREAD

**Issue by Lee182** [cerebral/overmind#270]
Hello I've just been to overmindjs.org and the first page has this.

> AMAZING DEVELOPER EXPERIENCE
Develop your app without the browser. Just connect directly to your app to focus on state, effects and actions development. Run your actions and verify that state changes and effects are run correctly. Or open up your app and debug state, effects and actions with your running application.

I've looked around the website and found no documentation for how I run the overmind-devtools app which are shown in the video guides. So for me not an amazing developer experience getting started.

**Comment by eirikhm** [comment]
Install the package, and run `yarn overmind-devtools` :-)

**Comment by christianalfoni** [comment]
@Lee182 Hehe, very good point :) 

I am adding a `quickstart` guide for people who just wants to get going. Currently it is intertwined with the general get started guide, but understand many developers do not want to go through all that :)
