### ISSUE TITLE
docs on multiple state files

### ISSUE THREAD

**Issue by SteveALee** [cerebral/overmind#271]
In the [state article](https://overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=false) you show how to define but not how to merge into the single tree. Or is it done on filename?

**Comment by SteveALee** [comment]
Similar with [Structuring the app](https://overmindjs.org/guides/beginner/06_structuringtheapp?view=react&typescript=false) hwre at the end it shows how to nest and namespace but not how to reference child state

**Comment by christianalfoni** [comment]
Ah, thanks for noting that. I made a few updates related to this. I can totally see that was confusing :)
