### ISSUE TITLE
Guides: Get started, not possible to disconnect devtools

### ISSUE THREAD

**Issue by fopsdev** [cerebral/overmind#275]
Hi there

Really Enjoying the Getting Started Guide.
Though i'm not able to disconnect from the devtools.
It looks like this for me:
![image](https://user-images.githubusercontent.com/5448300/59207559-90675080-8ba7-11e9-9758-24c022be2f63.png)
As well, why is it necessary to disconnect? Thats not 100% clear to me.
Maybe its because i'm running from parceljs and have the site running inside the brwoser already?

Really cool stuff! Keep it up!

**Comment by fopsdev** [comment]
Currently as well blocked with react UI and parcel...
Will try to solve the issue and continue the guide later.

**Comment by eirikhm** [comment]
Disconnect should not necessary. Some changes coming soon, stay tuned :-)
