### ISSUE TITLE
Lazy.loadConfig does not return loading promise! 

### ISSUE THREAD

**Issue by JeronimoBlack** [cerebral/overmind#283]
There for is not possible to load a lazy module and call an action, effect or access it's state! 

Ex.:
await actions.lazy.loadConfig("aLazyModule") ;
actions.aLazyModule.doSomething() ;

**Comment by christianalfoni** [comment]
Hi there and thanks for reporting!

There are tests written for this, though it is not a common feature. What kind of error are you receiving? If you could create a codesandbox example that would be even awesomer :)

Will nevertheless look into this before next release :)

**Comment by christianalfoni** [comment]
Hm, I looked at this and not able to reproduce. I also added an action execution to the test, just to make sure. Would be great with a Codesandbox example to help you out on this one :)

**Comment by JeronimoBlack** [comment]
Here is the test project:

**Comment by christianalfoni** [comment]
Aha! I see now, I will look into this ASAP. We have a pending release and will make sure this is part of it :)

**Comment by christianalfoni** [comment]
Okay, @JeronimoBlack , if you install `npm install overmind@next and overmind-react@next` things should work as expected :)

Thanks a bunch for reporting this as this was clearly not working as intended!

**Comment by christianalfoni** [comment]
Closing this as the fix was part of the previous release :)
