### ISSUE TITLE
It is not possible to fix deprecation warning

### ISSUE THREAD

**Issue by SurenAt93** [cerebral/overmind#293]
I have recently updated overmind/overmind-react versions on one of my projects.

```
"overmind": "^18.0.1"
"overmind-react": "^19.0.1"
```

After that update I received this deprecation warning:

```
DEPRECATION - Do not pass the overmind instance to "createHook", but use the provider. Please read docs for more information
```

from lib source:

```
export const createHook = (overmindInstance) => {
    if (overmindInstance) {
        console.warn('DEPRECATION - Do not pass the overmind instance to "createHook", but use the provider. Please read docs for more information');
    }
    let currentComponentInstanceId = 0;
```

Previously I created store hook like [this](https://github.com/SurenAt93/monaco-react/blob/master/demo/src/store/index.js#L12):

```
import { createOvermind } from 'overmind';
import { createHook } from 'overmind-react';

import { initialState } from './state';
import * as actions from './actions';

export const store = createOvermind({
  state: initialState,
  actions,
});

export const useStore = createHook(store);
```

After this depreciation warning, I tried to remove the instance from "createHook" as docs [shows](https://overmindjs.org/guides/beginner/08_usingovermindwithreact?view=react&typescript=false), but I face this issue:

```
TypeError: Cannot read property 'mode' of undefined
```

From lib source:

```
const overmind = (overmindInstance || useContext(context));
if (overmind.mode.mode === MODE_SSR) {
  return {
    state: overmind.state,
    actions: overmind.actions,
    effects: overmind.effects,
    addMutationListener: overmind.addMutationListener,
};
```

Thank you!

**Comment by christianalfoni** [comment]
Hi there!

Yes, this deprecation caused some confusion. Sorry about that :-/

You also have to provider overmind on the context of React using the Provider, as also mentioned in the docs there:

```js
import React from 'react'
import { render } from 'react-dom'
import { createOvermind } from 'overmind'
import { Provider } from 'overmind-react'
import { config } from './overmind'
import App from './components/App'

const overmind = createOvermind(config)

render((
  <Provider value={overmind}>
    <App />
  </Provider>
), document.querySelector('#app'))
```

We will add a better error message here to notify that you are missing the React provider :)

**Comment by SurenAt93** [comment]
@christianalfoni now it makes sense; everything works. Thank you! I am closing the issue.
