### ISSUE TITLE
Overmind action does not work with circular json due to devtool inspection?

### ISSUE THREAD

**Issue by louisgv** [cerebral/overmind#299]
It seems the DevTool is parsing every object or reference inside an action? When trying to fetch a circular json, I got this error:

![image](https://user-images.githubusercontent.com/6723574/61574174-6d667100-aa70-11e9-9f51-7589bc542f8f.png)

the json is returned from an internal API.

**Comment by christianalfoni** [comment]
I believe this is fixed 😄
