### ISSUE TITLE
BUG | Proxy state tree error regarding state mutation

### ISSUE THREAD

**Issue by louisgv** [cerebral/overmind#300]
Version: 20.0.1

![image](https://user-images.githubusercontent.com/6723574/61988285-37773e80-afd4-11e9-9de4-16fd7349fe6a.png)

**Comment by christianalfoni** [comment]
@louisgv Sorry about late answer here! I believe this is fixed now? Could you try again? :)

**Comment by christianalfoni** [comment]
Or if you are using Firefox: https://github.com/vuejs/vue-cli/issues/2012#issuecomment-410369818

Creating a fix for that now :)

**Comment by Suniron** [comment]
mmmmh i have the same issue :(

**Comment by christianalfoni** [comment]
@Suniron Hm, are you able to recreate the issue in a codesandbox?

**Comment by Suniron** [comment]
The wrong code was copied from a friend's project..
When I try with a lightest code, it's OK. 

So, no worry for me..

**Comment by christianalfoni** [comment]
Okay, great, thanks :) 

Closing this for now, please reopen if still an issue
