### ISSUE TITLE
cerebral-view-overmind

### ISSUE THREAD

**Issue by jeremy-coleman** [cerebral/overmind#302]
just an idea:
update https://github.com/cerebral-legacy/cerebral-view-snabbdom/blob/master/index.js to overmind and publish under the overmind umbrella.

why? I read an interview with you on medium, and greatly appreciate your thoughts on api stability.
the api stability of snabbdom + overmind would be great.

**Comment by christianalfoni** [comment]
Super late response! But I would encourage you to try to change it out. Use the `overmind-react` implementation as reference and try to make it work. Please ask me if you have any questions and I can help 😄
