### ISSUE TITLE
Question: Best way to add middleware for tracing

### ISSUE THREAD

**Issue by shiftyp** [cerebral/overmind#308]
I've built a small [example app](https://github.com/shiftyp/typr) using overmind, and my goal is to add tracing to the frontend using [opencensus](https://github.com/census-instrumentation/opencensus-web). Since overmind has powerful dev tools, there would appear to be a powerful way to plug into its operation and gather useful telemetry. What's the best way to plug into this functionality from the overmind configuration level?

**Comment by corlaez** [comment]
I am not sure what you want to achieve. I will state somethings that come to mind, let me know if any of these helps.

1. I skimmed openCensus and seems to be a source of effects. I would advise to wrap it's api as effects.
2. Once this is an effect you can pull it from any action context ({effects}) => ... and use it in any of your actions.

There is not really a 'middleware' in overmind that I am aware of. But by wrapping this api in an effect you can mock it when necessary and you can access it from any action that may need it.

**Comment by christianalfoni** [comment]
@shiftyp Hi there!

You can use the events of Overmind to do this. We do it at  `codesandbox.io` to create a breadcrumb of action executions and state changes to understand error reports better. https://overmindjs.org/api-1/events
