### ISSUE TITLE
https://overmindjs.org/ is down when using cloudflare dns (1.1.1.1)

### ISSUE THREAD

**Issue by xaviergonz** [cerebral/overmind#312]
site seems to have been down for a few days now with error:

overmindjs.org’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by xaviergonz** [comment]
Apparently it only happens with cloudflare dns 1.1.1.1 :-/

**Comment by christianalfoni** [comment]
Believe this stuff is working again 😄
