### ISSUE TITLE
HMR connection error with Parcel

### ISSUE THREAD

**Issue by stephan281094** [cerebral/overmind#317]
Hey there! Thanks for creating Overmind!

I'm currently using Overmind in combination with [Parcel](https://parceljs.org) and it's working pretty well. However, whenever I open DevTools I get the following error:
```
WebSocket connection to 'ws://localhost:3031/?name=Overmind%20issue' failed:
Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

My guess is that this WS connection is used for HMR in combination with Webpack? It would be nice to prevent Overmind from trying to do this in other bundlers.

In case you want to check it out yourself, here's a repository where this can be reproduced: https://github.com/stephan281094/overmind-issue.

**Comment by christianalfoni** [comment]
Ah, 

this happens because by default in development Overmind always tries to reach the devtools. So you will have this error when you do not run the devtools. 

You can change to:

```ts
createOvermind(config, {
  devtools: false
})
```

To prevent it 😄
