### ISSUE TITLE
Throwing from Action results to uncatchable Error

### ISSUE THREAD

**Issue by mieky** [cerebral/overmind#318]
It looks like it's not possible to catch an Error thrown from an Overmind action (whereas Throwing from an Effect seems to catch all nice & good). Instead, the Error propagates all the way up to becoming an Unhandled Rejection.

I created a small Sandbox to replicate this with overmind & overmind-vue at 19.2.0 (although I think this also applies to other environments such as React):
https://codesandbox.io/embed/overmind-vue-issue-throwing-from-actions-zgtvm

Look into `components/HelloWorld.vue`:
- if you click on "Throw from local view", it's caught happily
- if you click on "Throw from Overmind action", the Error breaks through unhandled

```js
  methods: {
    throwLocally() {
      throwError().catch(err => {
        this.status = "Successfully caught error: " + err.message;
      });
    },
    throwFromOvermind() {
      this.actions.throwError().catch(err => {
        // never gets called, but should?
        this.status = "Successfully caught error: " + err.message; 
      });
    }
```

Please tell me if I'm doing something fundamentally silly...

**Comment by mieky** [comment]
This was fixed in v20.0.0 (https://github.com/cerebral/overmind/commit/dbd32755c6ef5f8f21193ddeac6167d2027ecbf3)!

To verify, I forked the original Sandbox and updated it to the newest release: https://codesandbox.io/s/overmind-vue-throwing-from-actions-fixed-in-v2000-x4612

Cheers @christianalfoni, thanks for the good work 😊

**Comment by mieky** [comment]
I might have been wrong in my claim that Effects do not leak exceptions – now it looks like I have a similar issue with an Error thrown from an Effect. I'll investigate further and maybe report a separate issue about it.

**Comment by christianalfoni** [comment]
@mieky Thanks for looking into it! Did you find any issue with it?

**Comment by mieky** [comment]
@christianalfoni Tried hard to replicate it, but couldn't, so it should be all fine 😊 Thanks for checking in!

**Comment by mpinter** [comment]
Hi - sorry for bothering on a closed issue, but we've encountered something which may be related to this on the newest version - but now, the error actually gets caught in the catch clause. Despite that, it also propagates onward as uncaught somehow - https://github.com/cerebral/overmind/issues/392

@mieky I was wondering whether you might have run into this recently

**Comment by mieky** [comment]
Hey @mpinter, wish I could be of help, but haven't used the latest versions recently. Would you be able to create a reproducible version of it, e.g. on codesandbox?

**Comment by mpinter** [comment]
Sure, here it is - https://codesandbox.io/s/overmind-example-toloe?file=/src/components/App.js
