### ISSUE TITLE
Feature: Bindings for Overmind and GraphQL

### ISSUE THREAD

**Issue by Obiwarn** [cerebral/overmind#319]
This could probably bring a radical productivity boost?

Like in [mst-gql](https://github.com/mobxjs/mst-gql).

Westrate video on this: [@react-europe](https://www.youtube.com/watch?v=Sq2M00vghqY&list=PLCC436JpVnK3kcTnPyhcs7QnHK2PKl33D&index=12&t=0s)

**Comment by jhsu** [comment]
seems like overmind-graphql is researched/developed: https://www.youtube.com/watch?v=xidY_Ys5M10

**Comment by RyszardRzepa** [comment]
codesandbox from the graphql video: https://codesandbox.io/s/affectionate-dan-shhj7

**Comment by brasilikum** [comment]
Done: https://overmindjs.org/addons/graphql
Let's close this
