### ISSUE TITLE
Discord invite link invalid

### ISSUE THREAD

**Issue by ptcampbell** [cerebral/overmind#323]
The link to the Discord channel on https://overmindjs.org is invalid. 

<img width="521" alt="Screen Shot 2019-10-16 at 11 24 20 AM" src="https://user-images.githubusercontent.com/876594/66947386-a7abc400-f007-11e9-94ed-8ecc7fa864cf.png">

https://discordapp.com/invite/YKw9Kd

**Comment by popo63301** [comment]
The link has changed and it works now. 😬

**Comment by jonathanj** [comment]
This Discord invite has expired again, it looks like this is the same link as the one in the "Introduction" doc.
