### ISSUE TITLE
Overmind fails to hot reload if "root" element is a div rather than a section

### ISSUE THREAD

**Issue by eldrgeek** [cerebral/overmind#328]
Bug reproduced in [this sandbox](https://codesandbox.io/s/overmind-counter-div-and-section-rmsju) which was forked from the first demo on [this page on the overmind site](https://overmindjs.org/introduction?view=react&typescript=false).

1. Buttons increment and decrement counter
2. Modify index.js in any way (even a new line)
    Button stops updating
3. Change `private/index.html` line 30 from:
`<div id="root"></div>`
to
`<section id="root"></section>`

Now any changes to index.js are hot updated properly including changes to state, and actions.

Here's [a video demo](https://www.hippovideo.io/video/play/Qr0Rsn5iXR7Ln3HpWXUeag) of the procedure.

The Todo List demo operates properly and uses a section, not a div

Anything other than a div (e.g. span, or aside or even blurffflebe) seems to work. Just don't use a div.

**Comment by christianalfoni** [comment]
@eldrgeek 

Hm, I believe this might be related to React instead? But no matter, waaaay too edge casy to dive into 😅 

But good catch! 😄
