### ISSUE TITLE
🌈Feature: tag which node in the state has reactions attached

### ISSUE THREAD

**Issue by yeion7** [cerebral/overmind#331]
*Devtools*

Right now we can see witch nodes are derived states, I would like see which nodes has reactions attached in the same way

![image](https://user-images.githubusercontent.com/9127504/68164161-22db0880-ff2a-11e9-9d97-7bb5da95a541.png)

**Comment by christianalfoni** [comment]
@yeion7 Hi there!

That is a very interesting suggestion. I was thinking that `reactions` would rather be like a separate tab, like components. Where you get a list of active reactions? 

Does that make sense?

**Comment by yeion7** [comment]
Yes, it sounds like a better solution

**Comment by christianalfoni** [comment]
Okay, it is noted and will be part of some future release 😄
