### ISSUE TITLE
Question: Overmind and React Concurrent Mode

### ISSUE THREAD

**Issue by Thisen** [cerebral/overmind#333]
Hi,

I have only just discovered Overmind and I was wondering how Overmind would work with the announcements in regards to React Concurrent Mode.

I have the following questions:

* Does Overmind effects support Suspense?
* Does Overmind support the [render-as-you-fetch](https://reactjs.org/docs/concurrent-mode-suspense.html#approach-3-render-as-you-fetch-using-suspense) pattern pushed by Concurrent Mode?

I would like to hear your thoughts.

**Comment by kiliman** [comment]
@Thisen @christianalfoni has created a YouTube video discussing his thoughts on Suspense and Concurrent mode.

https://www.youtube.com/watch?v=_XKL9tJ0Y4g

**Comment by christianalfoni** [comment]
@Thisen This is the third iteration: https://www.youtube.com/watch?v=O7J4RzYkFGs

Yeah, Overmind will support concurrent mode and suspense. The only issue it will have with suspense is working with "non Overmind suspend". The reason being that the component basically throws an error, which means the component will not be able to clean up the "tracking tree" produced initially. That said, suspense is not a set API yet and other libraries would have the same issue, so I would expect there to be some solution to this. THAT said, it would not be a real problem as a tracking tree has an extremely low memory footprint. We could also implement functionality which cleans up "loose tracking trees" related to suspense.

**Comment by christianalfoni** [comment]
Closing for now, React has introduced Strict Mode which where we will be compatible soon 😄
