### ISSUE TITLE
Overmind VS Code extension is missing vertical scroller

### ISSUE THREAD

**Issue by ppasieka** [cerebral/overmind#336]
My state is pretty big and I always have to collapse nodes to access other ones placed a bit lower on the state tree.

A similar issue is on the Components tab. When I Expand component I can't scroll to see what is on the bottom of the page

**Comment by saitodisse** [comment]
Same error here on xfce, linux

**Comment by exdeniz** [comment]
OSX too, VS Code Insider last, 0.0.25

**Comment by christianalfoni** [comment]
Believe this is fixed?
