### ISSUE TITLE
Question: Using Overmind state and Vue with Class Component

### ISSUE THREAD

**Issue by aislanmaia** [cerebral/overmind#338]
Hi all,

I have an app using Vuex and `vuex-module-decorator`, plus we are using Typescript with Vue, so we get free typing and things like Class Components (through packages like `vue-class-component` or `vue-property-decorator`. Here is some of the components we are communicating with vuex state:
```
import Component from "vue-class-component";
import { Infosets } from "@/store/infosets.store";
...etc...

@Component({
  components: {
    InfosetsTable,
    ...etc...
  }
})
export default class InfosetListContainer extends Vue {
  @Infosets.Getter public errorMessage;
  @Infosets.State public status;
  @Infosets.State public infosets;
  @Infosets.State public limit;
  @Infosets.State public page;
  @Infosets.State public totalPages;
  @Infosets.State public membersAvailable;

  @Infosets.Action
  public fetchAllInfosets: (params: { limit: number, page: number }) => Promise<void>;

  @Infosets.Action
  public searchInfosets: (searchTerm: string) => void;

...omitted for brevity...
}
```

As you can see, Typescript works great with Vue. 
But reading the Overmind docs I found this in the section of [guide](https://www.overmindjs.org/guides/beginner/10_usingovermindwithvue?view=vue&typescript=false) for using with Vue.
```
import { connect } from '../overmind'

export default connect(({ state, actions, effects }) => ({
  state: state.admin,
  actions: actions.admin
}), {})
```
My question is how we can use this `connect` (or something else) with the Class Components of Vue, for now.

PS: Maybe should be cool to have some decorators like the libraries above that get the things together.

**Comment by christianalfoni** [comment]
The story of Vue and typing requires more attention. With the new composition API as well it will get a review shortly
