### ISSUE TITLE
Uncaught Error: proxy-state-tree - You are mutating the path 

### ISSUE THREAD

**Issue by popo63301** [cerebral/overmind#340]
Hey !

I want to sort a list of data so that it is rendered correctly in my component but I don't want to modify it on my overmind state. By simply doing a sort(comp) call, I get this error:
```
Uncaught Error: proxy-state-tree - You are mutating the path "editPage.me.categories.sort", but it is not allowed. The following could have happened:
        
        - You are passing state to a 3rd party tool trying to manipulate the state
        - You are running asynchronous code and forgot to "await" its execution
        
```

I get this error from cypress btw

**Comment by popo63301** [comment]
I find it quickly. So, just need to copy the array like this: [...myStateArray]. Which I did, but I forgot to do it elsewhere. 😬

**Comment by christianalfoni** [comment]
👍

**Comment by rajputAkash1201** [comment]
I am getting this error when binding a state with an input field and trying to update the state value. Can You help???

**Comment by eirikhm** [comment]
Can you show some code? Likely you are not using an action to change the state.

**Comment by rajputAkash1201** [comment]
<input type="text" name="email" bind:value={$state.form.userName}>

This is how I am binding the state with svelte input.

**Comment by rajputAkash1201** [comment]
[](url
![Code](https://user-images.githubusercontent.com/79309864/184841345-02887ee4-0ad0-4afe-8208-0a5e3b83069e.png)
)

This is how I am binding the state with svelte input
