### ISSUE TITLE
Question: is the overmind state machine compatible with xstate?

### ISSUE THREAD

**Issue by Jimmy89** [cerebral/overmind#341]
I'm currently experimenting with xstate state machines ([xstate](https://github.com/davidkpiano/xstate)) and I'm wondering what the compatibility is with the overmind state machine. 
I think both packages could accelerate each other and I would be nice to see them working together.

**Comment by christianalfoni** [comment]
Good question though tall order 😄 

XState is very much focused on being specification compatible, while in Overmind we try to make it as usable as possible in the current ecosystem. Basically, we have different goals 😄 

But statemachines and statecharts are continuing to inspire libraries and I think future state management solutions will be more aligned. Just like `Observables` became a thing... also `Promises`. Where many different implementations of those, but now they are aligning 😄
