### ISSUE TITLE
Lazy loaded module has wrong execution context!

### ISSUE THREAD

**Issue by cernymilan** [cerebral/overmind#342]
Context of any action contains execution with helpfull properties like "namespacePath:string[]", or "actionName:string". 
But when a module is lazy loaded the execution context has not set these properties! 
namespacePath is empty
actionName does not contain the module (namespace) part.
Normal (not lazy loaded):
![NotLazyLoaded](https://user-images.githubusercontent.com/168372/70434052-7e496a80-1a83-11ea-8b37-40a0aafcc92e.PNG)
![NotLazyLoadedExecutionContext](https://user-images.githubusercontent.com/168372/70434074-8903ff80-1a83-11ea-8006-b2bfc0f2cfac.PNG)

Lazy loaded:
![LazyLoadedModule](https://user-images.githubusercontent.com/168372/70434110-9caf6600-1a83-11ea-9680-cb47a34b3e2f.PNG)
![LazyLoadedExecutionContext](https://user-images.githubusercontent.com/168372/70434119-9faa5680-1a83-11ea-8815-50ec635ddff5.PNG)

**Comment by christianalfoni** [comment]
Sorry about exceptionally late response here!

Will fix this after next release 😄

**Comment by christianalfoni** [comment]
Okay, so a fix for this is running in `next` now. Please test by installing all overmind packages sing `@next` tag. When this is ready: https://travis-ci.org/github/cerebral/overmind/builds/724484819

**Comment by christianalfoni** [comment]
Released
