### ISSUE TITLE
devtools-vscode:  state object overflows without ability to scroll

### ISSUE THREAD

**Issue by mct-dev** [cerebral/overmind#350]
Any chance we could add the ability to scroll here? Long state objects will overflow on the Y axis and then you can't scroll down.

![image](https://user-images.githubusercontent.com/18542061/71423256-fba4db80-263c-11ea-9d14-c4adffd6fed5.png)

**Comment by rakasiwi23** [comment]
yup, I need this too.

**Comment by mct-dev** [comment]
This appears to be fixed now.  Maybe a new version of vscode.
