### ISSUE TITLE
Reactions which monitor entire state pass undefined to updateCallback

### ISSUE THREAD

**Issue by craigsumner** [cerebral/overmind#353]
For example, the following will print the real state to the console once, during the 'immediate' callback, but then print undefined for all future callbacks.

```
  const stateCallback = (state) => {
    return state;
  };
  const updateCallback = (value) => {
    console.log(value);
  }
  const options = {
    nested: true,
    immediate: true,
  };
  overmind.reaction(stateCallback, updateCallback, options);

```

**Comment by christianalfoni** [comment]
Sorry for late response! 

Noted as bug, will fix after next release!

**Comment by christianalfoni** [comment]
Okay, this is now running in `next` after: https://travis-ci.org/github/cerebral/overmind/builds/724489370

Please install packages with `@next` to test it.

**Comment by christianalfoni** [comment]
Released
