### ISSUE TITLE
Using classes as state properties

### ISSUE THREAD

**Issue by avele** [cerebral/overmind#358]
For example I have following code: 
```js
class TestObject {
  constructor (prop) {
    this.prop = prop
  }
}

const overmindConfig = {
  state: {
    testObject: null
  },
  actions: {
    initTestObjectAsClass({ state }) {
      state.testObject = new TestObject('initialPropValue')
    },
    initTestObjectAsPlainObject({ state }) {
      state.testObject = { prop: 'initialPropValue' }
    }
    setTestObjectProp({ state }, val) {
      if (state.testObject) {
        state.testObject.prop = val
      }
    }
  }
}
```

If I use `initTestObjectAsPlainObject` and then call  `setTestObjectProp` my component displaying `testObject.prop` rerenders automatically and displays new value of `prop`. But if I use `initTestObjectAsClass` method for initialization calling `setTestObjectProp` doesn't trigger rerender and component displays old value, although using devtools I can see that state value was changed.

Why does it work like that? Is it expected behavior and I just shouldn't use classes or is this bug? 

One of workarounds I found is to use destructuring like this `state.testObject = {...new TestObject('propVal')}`, but I don't feel like it's a good solution, since you need to duplicate it everywhere and I think it won't work with nested object.

**Comment by christianalfoni** [comment]
Overmind officially support classes now, so please reopen if this is still an issue 😄
