### ISSUE TITLE
How to  add graphql subscryption

### ISSUE THREAD

**Issue by RyszardRzepa** [cerebral/overmind#359]
You are doing amazing work  Christian ! 👍 
I am looking on graphql implementation and wondering how to add a subscription.

Do you plan to support subscription any time soon?
Or maybe you can give suggestions on how to add graphql subscription to overmind?

**Comment by marbemac** [comment]
+1 - we're using URQL right now, which has it's own cache / state, etc. The idea of consolidating to overmind is appealing, but we can't because we currently leverage urql subscription capabilities.

**Comment by brasilikum** [comment]
This is now possible: 
https://overmindjs.org/addons/graphql#subscription
