### ISSUE TITLE
Dynamic getters typings issue

### ISSUE THREAD

**Issue by Noviel** [cerebral/overmind#361]
overmind@22 has broken typings for dynamic getters, e.g. `value: Derive<State, (arg: any) => any>`

https://codesandbox.io/s/overmind22-derived-issue-yulef

`src/index.ts` is using `app.state.derivedDynamicValue('?')` which is incorrectly infrerred to accept as parameters `state` and `parent` instead of a string.

**Comment by christianalfoni** [comment]
I believe this is fixed now @Noviel? Also released. Please verify 😄

**Comment by Noviel** [comment]
Yeap, it is fixed, thx!  👍
