### ISSUE TITLE
[BUG] Statemachine reset doesn't actually reset the statemachine

### ISSUE THREAD

**Issue by sazzer** [cerebral/overmind#364]
The documentation for the Statemachine says:

> You can reset the state of a statemachine, which also runs the exit of the current transition:

However, the code does *not* change the current state at all. As best I can tell from the code, it seems to do nothing more than run the Exit handler if there is one.

This means if I have a Statemachine to model the current state of a view, there is no safe way to reset back to the initial state when re-rendering the view. I'd need to support a transition back to the initial state from every other one, even if ithat's not technically correct - e.g. transitioning from a 'pending' state.

**Comment by christianalfoni** [comment]
Hi @sazzer and thanks for the feedback!

Sorry about, this is already fixed and pending release here: https://travis-ci.org/cerebral/overmind/builds/648354077
