### ISSUE TITLE
[BUG] new proxying of classes breaks, perhaps add opt out proxy for prop?

### ISSUE THREAD

**Issue by marbemac** [cerebral/overmind#367]
We're attempting to upgrade from `21.0.0` to `22.0.5`, but are running into an issue. Basically, overmind is attempting to proxyify the classes that we have in our state, and in some cases these classes are not proxyify-able. In fact there is really no reason to do the work to proxify / track these properties in our case (beyond perhaps a reference track on the root prop, without tracking stuff in the class itself).

Here's an example state object - `TreeStore` is from another package that we use. We could of course move `treeStore` out of the overmind state object, but then we need to come up with another way to pass these values around outside of the overmind stores, which is kind of a bummer since overmind is easy to access from components, etc.
 
```ts
export const state: State = {
  treeStore: new TreeStore({
    defaultExpandedDepth: 2,
  }),
  search: {
    value: '',
    query: '',
  },
};
```

Results in this error in proxy tree as of latest overmind 22.0.5:

<img width="1593" alt="Screen Shot 2020-02-13 at 5 56 11 PM" src="https://user-images.githubusercontent.com/847542/74489843-37fdf680-4e8c-11ea-9665-c2e0e2d4db4b.png">

I see that you put a special exception for Date objects here - https://github.com/cerebral/overmind/commit/795fd91e4562b2ec2e9c75660ce69a8527d16849 - perhaps it makes sense to come up with a more general way to opt out of state tracking for particular properties? Feels like there is a use case for it.

**Comment by christianalfoni** [comment]
Oh! Hi there! :)

I have pushed a fix to `next` now which checks if the class instance is extensible 😄

**Comment by marbemac** [comment]
Didn't quite work out of the box (because the class is extensible, but some of the properties on the class are not). However, this provided a nice escape hatch, which does the trick. A safer and more future proof implementation might check extensibility while proxifying rather than once at the top level? Assuming there is no meaningful performance penalty etc.

For right now, with the change in latest next, can manually wrap parent class to stop the proxifying:

```ts
export const state: State = {
  treeStore: Object.preventExtensions(
    new TreeStore({
      defaultExpandedDepth: 2,
    }),
  ),
  search: {
    value: '',
    query: '',
  },
};
```

**Comment by christianalfoni** [comment]
Oh, interesting! Did not know about that API 😄 👍 

Though, exactly how did it break here now? Cause the class instance was not proxied anymore, right? Or was it still proxied? Cause the update to `next` should have ensured that the class was not proxified

**Comment by christianalfoni** [comment]
Closing this for now, please reopen if still issue 😄
