### ISSUE TITLE
[BUG] overmind-angular: @angular core has no exported member 'Renderer'

### ISSUE THREAD

**Issue by jonasdaugalas** [cerebral/overmind#368]
### Reproduce
- Create new angular project with Angular CLI https://cli.angular.io/
- Follow the Overmind tutorial https://overmindjs.org/views/angular
- Get the following error:
```
ERROR in node_modules/overmind-angular/lib/directive.d.ts:1:41 - error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
    
    1 import { ViewContainerRef, TemplateRef, Renderer, OnInit, OnDestroy } from '@angular/core';
                                              ~~~~~~~~
    
      node_modules/@angular/core/core.d.ts:5692:31
        5692 export declare abstract class Renderer2 {
                                           ~~~~~~~~~
        'Renderer2' is declared here.

```
### Context
`package.json`:
```
...
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "overmind": "^22.0.5",
    "overmind-angular": "^22.0.5",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
...
```

**Comment by christianalfoni** [comment]
Hi there!

Sorry about late response here.

It is really difficult building libraries for Angular, cause they keep changing the API and types. But will update this on next release to support latest typing 😄

**Comment by andrewvmail** [comment]
Was just experimenting, I got it working with these, aot off, ivy false and I remember having issues with aot in cerebral as well. 

https://github.com/andrewvmail/overmind/commit/6fcb64632963fe0e3c4f5d4dc3cde7560e9c6dea
https://github.com/andrewvmail/overmind-angular-demo

**Comment by christianalfoni** [comment]
The latest release of `overmind-angular` is now built with `ng` and should support latest Angular version 😄
