### ISSUE TITLE
Examples of using Derived state, namespaced and TypeScript all together would be useful

### ISSUE THREAD

**Issue by sazzer** [cerebral/overmind#370]
I can see from the documentation how to get derived state working. That looks pretty simple.

I can see from the documentation how the `Derive<>` type should work when doing this with TypeScript. That doesn't seem *too* complicated.

I can't work out how to make this work in a nested area of a namespaced state, and especially when I'm trying to depend on parts elsewhere in the state.

I'm also struggling to get this to work correctly with the TypeScript type system - my code is ending up with a value of type `Derive<>` instead of the correct type, and so I can't easily reference into it.

Some of this I worked out from the examples in https://github.com/cerebral/overmind/blob/next/packages/node_modules/overmind/src/derived.test.ts, but it would be very helpful to have one that shows both the use of `namespaced()` *and* actually making use of the value that the derived property is supposed to be returning.

Cheers

**Comment by christianalfoni** [comment]
Thanks for writing up the issue @sazzer and sorry for my late reply!

Tomorrow there will be a new release of Overmind which changes the derived API related to a new typescript version. Hopefully that will clear it up, if not, please reopen the issue 😄
