### ISSUE TITLE
Cmd+h to hide window in macOS doesn't work

### ISSUE THREAD

**Issue by veloek** [cerebral/overmind#373]
I suspect that the "cmd+click to edit state" feature is blocking the default behavior.

**Comment by christianalfoni** [comment]
Hm, weird, will check 😄

**Comment by christianalfoni** [comment]
Okay, cool, this is in next when this is ready: https://travis-ci.org/github/cerebral/overmind/builds/724496217

Try it out with `npx overmind-devtools@next`

**Comment by christianalfoni** [comment]
This should be out 😄
