### ISSUE TITLE
[BUG] Exposing Axios as an effect does not expose Axios' methods.

### ISSUE THREAD

**Issue by vibl** [cerebral/overmind#375]
The example described in https://overmindjs.org/core/running-side-effects#exposing-an-existing-tool triggers an error: `effects.http.get is not a function`.

Apart from that, I absolutely love Overmind!

**Comment by christianalfoni** [comment]
Thanks for the issue! Will need to look into that, thanks! 😄

**Comment by christianalfoni** [comment]
Hi there!

Do you have an example? I was unable to reproduce this. Please reopen if still an issue 😄
