### ISSUE TITLE
Where to Run this command Overmind Devtools: Start

### ISSUE THREAD

**Issue by jsbimra** [cerebral/overmind#376]
not sure where exactly we need to run this one.

**Comment by jsbimra** [comment]
Getting following error:

`Devtools.ts:30 WebSocket connection to 'ws://localhost:3031/?name=Overmind%20React%20app%20-%20Jat' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Devtools.connect @ Devtools.ts:30
initializeDevtools @ index.ts:766
Overmind @ index.ts:291
createOvermind @ index.ts:179
./src/index.js @ index.js:10
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
1 @ serviceWorker.js:141
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1 OVERMIND DEVTOOLS: Not able to connect. You are trying to connect to "localhost:3031", but there was no devtool there. Try the following:
        
          - Make sure you are running the latest version of the devtools, using "npx overmind-devtools@latest" or install latest extension for VSCode
          - Close the current tab and open a new one
          - Make sure the correct port is configured in the devtools`

**Comment by brasilikum** [comment]
In order to be able to debug Overmind you need to run the VSCode Overmind extension.

**Comment by deadcoder0904** [comment]
Download Overmind VSCode extension from [here](https://marketplace.visualstudio.com/items?itemName=christianalfoni.overmind-devtools-vscode)

Now, inside VSCode, type <kbd>CTRL + SHIFT + P</kbd> (Win/Linux) or <kbd>CMD + SHIFT + P</kbd> (Mac)

Finally, type `Overmind Devtools: Start` & press `Enter` <kbd>⏎</kbd> to run Overmind.

> Note: You might need to refresh your browser if Overmind doesn’t connect. Happens to me sometimes while I’m working with Overmind + Electron combo :)

**Comment by jatsgit** [comment]
cool thanks Easy peasy! :D

**Comment by jatsgit** [comment]
> Download Overmind VSCode extension from [here](https://marketplace.visualstudio.com/items?itemName=christianalfoni.overmind-devtools-vscode)
> 
> Now, inside VSCode, type CTRL + SHIFT + P (Win/Linux) or CMD + SHIFT + P (Mac)
> 
> Finally, type `Overmind Devtools: Start` & press `Enter` ⏎ to run Overmind.
> 
> > Note: You might need to refresh your browser if Overmind doesn’t connect. Happens to me sometimes while I’m working with Overmind + Electron combo :)

<img width="723" alt="Screenshot 2020-03-27 at 19 00 14" src="https://user-images.githubusercontent.com/1294763/77754094-3b74c800-705d-11ea-9941-fc3de262eaf3.png">

My application is running on port 9000 and i enter post 9001 for overmind under visual source code, what this means waiting app to connect what I need to do next?

**Comment by deadcoder0904** [comment]
did you connect overmind (i.e, added some state & the rest of the configuration like `Provider`’s, etc..) with your code? if not, then do that. it should definitely work if you reload it :)

**Comment by jatsgit** [comment]
Yes its did with that whole code is here: https://github.com/jatsgit/multi-doable-form let me know if i miss anything, thanks :)

**Comment by deadcoder0904** [comment]
Your `devtools` option is set to `false` [here](https://github.com/jatsgit/multi-doable-form/blob/master/pages/index.js#L20). Change it to `true` to make it work.

You can close this issue now :)

**Comment by jatsgit** [comment]
enabling to true still it shows same 

> Waiting for an app to connect to 9001...

app is running on port 9000 when i enter port 9000 to connect its says port already in use and don't see any screen or what to do, sorry completely newbie to this overmind tool

**Comment by henri-hulski** [comment]
Devtools are running by default on port 3031. This is not the port your app runs. It's different.
Try to set the port to 3031 or if you need an other port you can change it with

```js
const overmind = createOvermind(config, {
    devtools: 'localhost:9001'
});
```

**Comment by christianalfoni** [comment]
The next version of devtools changes up a little bit on how it informs on how to connect. Hopefully that will clear things up 😄

**Comment by MNF** [comment]
@christianalfoni can you add to instructions in https://marketplace.visualstudio.com/items?itemName=christianalfoni.overmind-devtools-vscode

**Inside VSCode, type CTRL + SHIFT + P (Win/Linux) or CMD + SHIFT + P (Mac)**
to run the command “Overmind Devtools: Start”
