### ISSUE TITLE
[BUG] overmind-graphql typing?

### ISSUE THREAD

**Issue by yovanoc** [cerebral/overmind#378]
I tried to use the graphql plugin, which I follow instructions on the documentation but I got this error:

![image](https://user-images.githubusercontent.com/7302317/76413898-92f51180-6396-11ea-96d2-75ab9198c206.png)

Thanks

**Comment by eXtreme** [comment]
Stumbled upon this issue today as well. Seems like this PR https://github.com/apollographql/graphql-tag/pull/285 introduced a more specific return type. I managed to "fix" the problem by downgrading graphql-tag to 2.10.1 and while webpack still complains:

![image](https://user-images.githubusercontent.com/197671/76977817-1fbf4280-6936-11ea-8a8b-759982ab7f14.png)

The code is built and works.

**Comment by avin-kavish** [comment]
You can explicitly specify the type to be any inline
 ```ts
export const query: any = gql``
```

**Comment by eXtreme** [comment]
@avin-kavish then what's the point of using typescript if not for strict typing? :) What is more, the official docs: https://overmindjs.org/addons/graphql#typescript suggest typing the query so obviously it does not work the way documentation say at the moment.

**Comment by avin-kavish** [comment]
Yeah, when I made that comment, I hadn't gotten to that point in the documentation :) The updated code would be,

```tsx
import { Query, gql } from 'overmind-graphql'
import { Posts } from './graphql-types'

export const posts: Query<Posts> = gql`
  query Posts {
    posts {
      id
      title
    }
  }
` as any;
```

**Comment by christianalfoni** [comment]
@eXtreme Hi there and thanks for reporting it!

Just wanted to say that I have seen the issue and will look at it as soon as I get a chance 😄

**Comment by mi-kas** [comment]
Any updates on this? The bug is really annoying especially if you use TypeScript in strict mode

**Comment by christianalfoni** [comment]
Hi there!

Sorry for the delay on this, but could you try the `next` version? Install all packages with `next`.

```sh
npm install overmind@next overmind-graphql@next overmind-react@next
```

**Comment by mi-kas** [comment]
> Hi there!
> 
> Sorry for the delay on this, but could you try the `next` version? Install all packages with `next`.
> 
> ```shell
> npm install overmind@next overmind-graphql@next overmind-react@next
> ```

Thanks, that resolved the issue 👍

**Comment by morgancmartin** [comment]
For anyone else who may have run into this, I can confirm this works for vue as well.

**Comment by christianalfoni** [comment]
Great stuff, it is released in latest version 😄
