### ISSUE TITLE
[FEATURE] Offline docs support on DevDocs/Zeal/Dash?

### ISSUE THREAD

**Issue by deadcoder0904** [cerebral/overmind#380]
Some days my internet is gone & I would love to have Overmind docs offline.

Would love if it supports [DevDocs](https://devdocs.io) :)

**Comment by deadcoder0904** [comment]
Another note: There are lots of Codesandboxes which won’t work without the internet.

It would be good if they were only code blocks with tabs without relying on the internet

**Comment by christianalfoni** [comment]
If gitbook evet gets offline support we will have it 😄 

It is just an insane amount of work to write docs and also moving it to new services, 

But you can run the docs locally I believe, by cloning this repo: https://github.com/cerebral/overmind-website. Not sure how, but at least you have all the docs 😄

**Comment by deadcoder0904** [comment]
Yep my internet is back. Although that setup you have is too complicated, could've been markdown files. I found some typos & wanted to report them but it wasn't easy to find which files to edit as that repo seems generated. Again too difficult for a noob to contribute.

Although, I love how the docs cover best practices & doesn't sound too professionally worded. And that setup was hellish. Bunch of weird errors haha :)

**Comment by christianalfoni** [comment]
It is not really required to use the repo to contribute with changes. You click the "edit on github" link on any page you want to contribute with a change. The structure of the repo is https://gitbook.io, so can not do much about that 😄

**Comment by christianalfoni** [comment]
Closing for now, completely depend on Gitbook to have any offline support 😢
