### ISSUE TITLE
integration with web components like lit-element

### ISSUE THREAD

**Issue by chase-moskal** [cerebral/overmind#383]
hello! overmind looks really cool!

i was wondering what kind of work would be involved to adapt overmind for usage with `lit-element` instead of react/angular/vue

cheers!

&nbsp; :wave: chase

**Comment by christianalfoni** [comment]
@chase-moskal Eyh! Please join our Discord and talk to **fops**, he is doing a lot with `lit-element`. Maybe you guys could put something together for the community? 😄

**Comment by superveetz** [comment]
:+1:  , any progress on this front?

**Comment by chase-moskal** [comment]
@superveetz — no... i became gotten busy, and settled for `mobx`

but it irritates me how bloated and huge mobx has become (like, more than 100KB just for damned proxy observables, i can't even fathom how)... and they don't even offer a proper esm distribution... so later on, i'm intending to refactor mobx out of my apps, in favor of a leaner replacement

i'll either adapt something like overmind, or i'll make a new minimalistic thing specifically designed for browser-native web components like lit-element and similar systems...
