### ISSUE TITLE
[BUG] Can’t enter Object in the Actions panel of VSCode extension. Always requires JSON

### ISSUE THREAD

**Issue by deadcoder0904** [cerebral/overmind#385]
So I tried to add just `object` like `{x:123,y:33}` to my action but it didn’t work.

But as soon as I converted it to `JSON` like `{”x”:123,”y”:33}` it works perfectly fine.

It would be better if I can just add an `object` like `{x:123,y:33}` & it automatically converts to `JSON` or something like that :)

**Comment by christianalfoni** [comment]
Hi @deadcoder0904 ,

Ah, yes, this is because we need to parse the code you write there. Maybe we could get around it with using `eval` instead, it is a bit hackier, but I see your point. It is added to the list 😄

**Comment by christianalfoni** [comment]
This is fixed in next version, coming tomorrow 😄
