### ISSUE TITLE
[Feature] Preact compat

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#387]
We're doing amp pages and testing using preact for it, first thing that breaks for us in the stack is overmind due to reliance on `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` in `createHook`.

A quick google and I don't see a clear replacement in Preact, but I'm sure theres some equivalent. Would you support a PR for that?

**Comment by christianalfoni** [comment]
It is on my list, should be pretty much a copy/paste from React and then handle that missing thing there 😄

**Comment by christianalfoni** [comment]
What a shitty answer by me to support my own open source work 😂 YES, I would love a PR... closing for now, hit me with a PR!
