### ISSUE TITLE
[FEATURE / RFC] Ability to derive state from root using namespaces

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#389]
Namespaces would be more useful for us if we could derive state in the root level state container using any namespace.

Maybe this is possible with a special thing I don't see, but if not, it makes sense in that:

- It represents the root, above the namespaces
- Putting logic at the root that crosses namespaces seems like the logical place for it (not in utility functions somewhere on the side)

Finally, in the extreme large state case it makes sense you could have more deeply nested namespaces (is it already possible?), which would create just a simple tree structure.

**Comment by christianalfoni** [comment]
Hm, you do get access to the root in derived? 

```ts
const state = {
  someDerived: (state, rootState) => {}
}
```

**Comment by gabriel-peracio** [comment]
Yep, this already works. I guess the docs might need to be more explicit about this, but you can have a thing (state/action/etc) in one namespace operating on/reading from another namespace if you want.

**Comment by christianalfoni** [comment]
Closing for now 😄
