### ISSUE TITLE
Vue with Typescript and overminjs... How to ? 

### ISSUE THREAD

**Issue by M0dM** [cerebral/overmind#390]
Hi,

I am very new with typescript and still experimenting on making it works with vuejs and overmind.
I am trying to use connect to make the connection between my vue component and overmind.

To do so, I have folowed this documentation :
[https://overmindjs.org/views/vue#connect](https://overmindjs.org/views/vue#connect)

Everything works when I try in the browser but, I can not get ride of this kind of typescript errors:

```bash
ERROR in /home/benoit/Svn/WebProducts/Dxf2DxfDev/gcodevisu/src/components/Player.vue(25,18):
25:18 Property 'actions' does not exist on type '{ play: () => void; pause: () => void; stop: () => void; }'.
    23 |         },
    24 |         stop: function () {
  > 25 |             this.actions.stop()
       |                  ^
    26 |         }
    27 |     }
    28 | }
```

Please find below my component code: 

```javascript
<template>
<div class="player">
  <a @click="play">Play</a>
  <a @click="pause">Pause</a>
  <a @click="stop">Stop</a>
  <input
    type="number"
    min="1"
    :max="state.maxLine"
    value="state.currentLine">
</div>
</template>
<script lang="ts">
import { connect } from '@/overmind'

const player = Vue.extend({
    methods: {
        play: function () {
            this.actions.play()
        },
        pause: function () {
            this.actions.pause()
        },
        stop: function () {
            this.actions.stop()
        }
    }
})

const Player = connect(
    ({ state, actions }) => (
        {
            state: state.viewer,
            actions: actions.viewer
        }
    ),
    player
)

export default Player
</script>
```

**Comment by M0dM** [comment]
Ok, I started to read more vue documentation and it seems those issues could be related to vue problems with typescript...

I will try to add more information on the issue if I find a good practice to do what I want to.

**Comment by M0dM** [comment]
Finally, I could not figured out how to use connect with a typed component.
I temporarily fallback to the global "declare module 'overmind'" way.

I would very appreciate if anyone could give an example using Vue.expand, vue-class-component or  the new vue-composition-api.

**Comment by christianalfoni** [comment]
This needs a lot more love and will get it. Doing a Vue typing review related to the new composition API! 😄

**Comment by M0dM** [comment]
Thanks a lot!
Good luck with this.

**Comment by christianalfoni** [comment]
Okay, so I have a version running on `next` now that exposes the following:

```ts
// overmind/index.ts

import { createStateHook, createActionsHook } from 'overmind-vue'

export const config = { ... }

export const stateRef = createStateHook<typeof config>()

export const actions = createActionsHook<typeof config>()
```

Now you can use this with your **setup**:

```ts
import { stateRef, actions } from './overmind'

export default {
  setup() {
    return { state: stateRef(), actions: actions() }
  }
}
```

The **stateRef** allows a callback:

```ts
import { stateRef, actions } from './overmind'

export default {
  setup() {
    const someNamespacedState = stateRef(state=> state.someNamespace)
    return { state: someNamespacedState, actions: actions() }
  }
}
```

You can also use it with jsx:

```ts
import { stateRef, actions } from './overmind'

export default {
  setup() {
    const state = stateRef()
    const { changeFoo } = actions()
    return () => <div onClick={() => changeFoo()}>{state.value.foo}</div>
  }
}
```

This needs testing, but at leats we got something running now 😄

**Comment by christianalfoni** [comment]
Vue 3 has been officially released now and the package will be updated for the next release, please track: https://github.com/cerebral/overmind/issues/473
