### ISSUE TITLE
[BUG] Throwing from async actions and effects causes uncaught errors (even when those are explicitly caught) - React

### ISSUE THREAD

**Issue by mpinter** [cerebral/overmind#392]
Hello,

minimal codesandbox example here - https://codesandbox.io/s/overmind-example-toloe?file=/src/components/App.js . The core of the issue is as follows:

```js
// in component
useEffect(() => {
    // the error is correctly caught here but also propagates as unhandled
    new Promise((resolve, reject) => {
      // if I throw directly from here I'll only get the console log from catch clause
      // throw new Error('uncomment to see correct behaviour')
      // if thrown from action I'll get the react overlay
      actions.exampleAction().catch(e => reject(e));
    }).catch(e => console.log(e));
  }, [actions]);

// overmind/index.js
export const config = {
  actions: {
    // if the action is sync all is well
    exampleAction: async ({ state, effects }) => {
      throw new Error("hello");
      // same behaviour when throwing from effects, whether awaited or not
      // effects.test();
    }
  },
  effects: {
    // when sync all is good, adding async keyword seems to break this ?
    test: async () => {
      throw new Error("hello");
    }
  }
};
```

This might be related to https://github.com/cerebral/overmind/issues/318 but the behaviour is slightly different - the error actually gets caught by the catch clause, but somehow it also propagates as unhandled. I'm also not sure if this may be related to React, the original issue was for Vue.

Thanks for the reply and for the library as well. Cheers.

**Comment by christianalfoni** [comment]
Thanks a bunch for the example! Will look at this for next release! 😄

**Comment by suevalov** [comment]
@mpinter @christianalfoni I can also confirm this is happening for our project.

It pretty much blocks us from raising exceptions in actions. By looking at codesandbox client I see that you intercept expectations pretty much everywhere: https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/overmind/namespaces/comments/actions.ts#L62

I'd like to help and fix this issue cause it's quite pressing for us. I would appreciate if @christianalfoni could give any leads (where to look at)

Thanks!

**Comment by suevalov** [comment]
So, I hunt this bug down to https://github.com/cerebral/overmind/commit/c725378ad7e24a4a290bf91dd292765ecd3a50a3

Removing this line fixes an issue

**Comment by suevalov** [comment]
I opened the PR but I might be missing some reasons why it was added at first place.

**Comment by christianalfoni** [comment]
Okay, I looked at this now. I changed it to this:

```ts
let result = action(context, scopedValue)

          if (isPromise(result)) {
            this.eventHub.emit(EventType.OPERATOR_ASYNC, execution)
            result = result
              .then((promiseResult) => {
                execution.isRunning = false
                if (!boundExecution) {
                  mutationTree.dispose()
                }
                this.eventHub.emit(EventType.OPERATOR_END, {
                  ...execution,
                  isAsync: true,
                  result: undefined,
                })
                this.eventHub.emit(EventType.ACTION_END, execution)

                return promiseResult
              })
              .catch((error) => {
                execution.isRunning = false
                if (!boundExecution) {
                  mutationTree.dispose()
                }
                this.eventHub.emit(EventType.OPERATOR_END, {
                  ...execution,
                  isAsync: true,
                  result: undefined,
                  error: error.message,
                })
                this.eventHub.emit(EventType.ACTION_END, execution)

                throw error
              })
```

Basically I want to intercept the promise to pick up the error that is thrown to show it in the devtools... but then I have to make sure we keep throwing it. I was just doing it the wrong way :)

This is pushed to `next` and you can test it by installing `@next` on all overmind packages. When this is done: https://travis-ci.org/github/cerebral/overmind/builds/699281102

**Comment by suevalov** [comment]
Great! I'll check out the next release and see if it works 👍

**Comment by suevalov** [comment]
Works as expected, thank you!

**Comment by christianalfoni** [comment]
Closing this for now as it will be part of next release 😄
