### ISSUE TITLE
[Feature] Statecharts: allow some actions to execute in any state

### ISSUE THREAD

**Issue by danclarkuk** [cerebral/overmind#394]
Some actions should not cause a state transition. These can be added to each state in the chart as actionName: null, but they have to be added to every state, which creates noise.

An example of where this might occur is where a websocket recv executes an action on the client side - for example a ping or an update - that should not cause a state transition.

Can we add some sort of mechanism that allows specific actions in any state? For example a list of actions allowed which do not cause a transition:

const chart = {
  initial: 'STATE_A',
states: {
    STATE_A: {...},
    STATE_B: {...}
  },
noTransitions: [ 'actionName', 'actionName2' ]
}

Feedback appreciated!

**Comment by gabriel-peracio** [comment]
Can't you simply use another namespace for those actions?

**Comment by grandevel** [comment]
@gabriel-peracio sure, but that feels like a workaround. Ideally I'd like all logic related to a domain in that domain, not some workaround actions in a separate domain.

A better solution for me has been to spread common actions into each state - 

STATE_A: { on: { someAction: blah, ...commonAllowedActions } } 

but still feels like it could be cleaner.

**Comment by christianalfoni** [comment]
The next release of Overmind will actually push Statecharts into its own package and the Statemachine API is getting a revamp. Looking at what people use statecharts for, I think they can be used more effectively with a statemachine. Especially the new one.

I will close for now, but please reopen after release tomorrow and call me out if this is a wrong assumption 😄
