### ISSUE TITLE
[BUG] Crash in proxyfyEffects

### ISSUE THREAD

**Issue by geirsagberg** [cerebral/overmind#397]
Hey Christian, hope you're doing good :) Ran into this head-scratcher today:

```
Unhandled Rejection (TypeError): Cannot read property 'Symbol(ORIGIN_TARGET)' of undefined
apply
src/proxyfyEffects.ts:25
  22 | const name = path.split('.')
  23 | const method = name.pop()
  24 | return cb({
> 25 |   func: target.bind(thisArg[ORIGIN_TARGET]),
     | ^  26 |   effectId,
  27 |   name: name.join('.'),
  28 |   method,
View compiled
addUser
src/overmind/actions.ts:9
   6 | }) => {
   7 |   const userName = prompt('Brukernavn')
   8 |   if (userName) {
>  9 |     const id = await saveUser({ userName })
  10 |     users[id] = { id, userName }
  11 |   }
  12 | }
View compiled
addUser
src/index.ts:592
▶ 22 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

Thought at first it had something to with using IndexedDB, but the crash persists after I removed it. Also tested the latest Overmind version in my Gaver app, and that one crashes too.

Minimum reproducible repo: https://github.com/geirsagberg/auth-man.git

just `yarn` and try to add a user, it crashes :(

**Comment by geirsagberg** [comment]
Rolling back to `overmind-react@^23` fixes the issue, by the way.

**Comment by geirsagberg** [comment]
@christianalfoni Any ideas about this one?

**Comment by christianalfoni** [comment]
Hi @geirsagberg and sorry for my late reply! Just had a huge backlog after Corona stuff and not having time to prioritize open source 😄 

There is a new release tomorrow and will prioritize this for next release, as you can see with my PRESSING label 😉 

I have a feeling `proxyEffects` simply tries to bind to a function that is bound to `undefined` .... which we should check. But I have to dive into the example you gave (great 👍 ) to be sure 😄

**Comment by geirsagberg** [comment]
A simple check for undefined at least stops my example from crashing. Made a PR :)

**Comment by christianalfoni** [comment]
Things working okay? You using `next` with the fix? 😄

**Comment by geirsagberg** [comment]
Doesn't look like it's merged yet?

**Comment by christianalfoni** [comment]
oh, haha, my bad 😂

**Comment by geirsagberg** [comment]
No worries :) Things look good now, thanks!
