### ISSUE TITLE
[BUG] Merge and Statecharts cause devtools error

### ISSUE THREAD

**Issue by grandevel** [cerebral/overmind#398]
const onInitialize = ({ actions, effects }: Context) => {
  console.log('inittttt');
  actions.stateChartA.someAction();
  actions.stateChartB.anotherAction();
};

export const useOvermind = createHook();
export const config = merge({ onInitialize }, namespaced({ stateChartA, stateChartB }));

Works, but generates an error in console:

statechart.js:295 Uncaught (in promise) TypeError: Cannot read property 'devtools' of undefined
    at runAction (statechart.js:295)
    at eval (index.js:846)
    at operator (operator.js:146)
    at run (index.js:701)
    at run (operator.js:100)
    at nextIsCalled (operator.js:110)
    at eval (index.js:816)
    at operator (operator.js:79)
    at run (index.js:701)
    at run (operator.js:100)
(on 23.1 released 10 mins ago, but happened on prev release too)

**Comment by christianalfoni** [comment]
Thanks for testing and writing up an issue! Next release will focus on statecharts, where this will also be fixed 😄

**Comment by christianalfoni** [comment]
Okay, this is fixed in next version. Wonder why it happens though. Only thing I can think of is hot reloading... or hm... possibly an `onInitialize` of one namespace running an action from your chart before the chart `onInitialize` has run. 

Could you verify? 😄

**Comment by grandevel** [comment]
Thanks @christianalfoni. Yes, I was trying to call an action from within onInit to work around https://github.com/cerebral/overmind/issues/396

**Comment by christianalfoni** [comment]
Ah I see! I am working on that now, so that should be fixed in next version as well 😄

**Comment by christianalfoni** [comment]
Closing this for now, will be part of next release
