### ISSUE TITLE
Spread operator issue [ES/React]

### ISSUE THREAD

**Issue by gersondinis** [cerebral/overmind#402]
### Spread operator issue [ES/React]
_To easily explain the behaviour I will numerate the code blocks. [1, 2, 3]_
> Needs: save a callable on state.

**1.** An **action** `addNotification` defined as:
```
addNotification: ({state}, {message, ...config}) => {
    state.app.notifications.push({message, config});
}
```
**2.** And the same **action** executed as:
```
actions.app.addNotification({
    message: 'Notification message',
    variant: 'success',
    content: (notification, state) => () => 'someDerivedValue'
});
```
**3.** And in a component just by **accessing the state** `content` as:
```
state.app.notifications.forEach(({message, config}) => {
    const someVariable = config.content;
}
```

**Result:** fires this **error** when executing _[Block:**3**  Line:**2**]_:
> TypeError: Cannot read property 'config' of undefined [src/derived.ts:35]

**Workaround**: is to **add spread operator** in the next lines:
> _[Block:**1**  Line:**2**]_: `state.app.notifications.push({message, ...config});`
> _[Block:**3**  Line:**1**]_: `state.app.notifications.forEach(({message, ...config}) => {`

**Question: _Anyone know why this occurs?_**

**Comment by christianalfoni** [comment]
@gersondinis Hi there!

This seems weird, hm. What happens when you log out `config` on point `1.`? Is it undefined there as well? 

Would be great with a https://codesandbox.io issue on this so we can play around with it together 😄

**Comment by gersondinis** [comment]
Sorry. I think you can close this 'issue' because it was my mistake. 
```
state.app.notifications.forEach(({key, message, ...config}) => {
    actions.app.removeNotification(key);
    enqueueSnackbar(message, config);
});
```
I was removing the notification from overmind state before using it when iterating the notifications array, so the error makes sense:
> Cannot read property 'config' of undefined [src/derived.ts:35]

And probably the spread operator was copying properties to a new object giving a different instance on local iterating scope preventig the error to occur.

One more time sorry for the false alarm bug.

**Comment by christianalfoni** [comment]
Ah, no worries, could happen to anyone, including me 😄
