### ISSUE TITLE
[BUG] type inference doesn't work for lazy configs

### ISSUE THREAD

**Issue by ju1ius** [cerebral/overmind#403]
When lazy loading a namespaced config, it is not possible to refer to the state, actions or effects of the namespace without causing a type error.

Please see [this example](https://codesandbox.io/s/modern-mountain-t98ny?file=/src/config/index.ts).
Here's a short description:
I have an auth namespaced module which handles authentication.
Once the state at path `state.auth.isAuthenticated` becomes `true`, an action is triggered to lazy-load the `user` module.
The `user` module then loads it's own state in it's own `onInitialize` callback.

The problem is that accessing `state.user` or `actions.user`, etc... triggers a compiler error: `Property 'user' does not exist on type '{...}'`.

The aforementioned codesanbox example works, but I have to put `//@ts-ignore` everywhere I want to access any state or action of my `user` module, which makes me sad...

**Comment by ju1ius** [comment]
One possible workaround is:
```ts
// in config/user/index.js
const userConfig = {state, actions, effects, onInitialize}
export default userConfig
export type UserConfig = {
  state: {user: typeof state}
  actions: {user: typeof actions}
  effects: {user: typeof effects}
}
```
then
```ts
// in config/index.js
import type {UserConfig} from './user'
export interface Config extends IConfig<typeof config & UserConfig> {}
```

But this is rather cumbersome... IMO this should work out of the box.

**Comment by christianalfoni** [comment]
Thanks a bunch for the issue and suggestion! Will look at this for next release!

**Comment by christianalfoni** [comment]
Released
