### ISSUE TITLE
[Feature] Identify which domain/namespace an action is being called within

### ISSUE THREAD

**Issue by grandevel** [cerebral/overmind#404]
I want to do is figure out how to understand which domain I am inside an action. Example:

I have two types of state in my app - but they are identical. One called Van and one called Car. Each is defined as state = { onBoardPeople: 0, onBoardNames: [], inMotion: false }, and actions addPerson(name) and setInMotion(isMoving). 

I try and be clever, so I create a single namespace - but export the config twice from index.js:

const config = { state, actions };
export const van = config;
export const car = config;

I then namespace them - namespaced({ car, van}));

Everything works great for state and derived state, but things break when I call an action - because the action does not know which domain it was called from and without passing in an object param every time (i.e. - actions.car.setInMotion({'car', true}), setInMotion has no idea whether it is being called in the car namespace or the van namespace.

Hence it would be really be nice to know which domain you are in inside an action - either with an instance or at least a keyname... like a destructure myAction = async({state, actions, effects, domain}) => {...}, and domain is the namespace actions, effects, etc if defined.

I appreciate this kind of goes against have 'globaised' actions and state, but derived state for example - this works well. It would also work well with actions!

**Comment by christianalfoni** [comment]
Hi @grandevel!

Log out the `context` of an action (the first argument of the action)  and you will find some information there that will help you 😄 

The only reason actions do not have a concept of "local state" is typing issues. You can not really automatically type it.

Please reopen if more questions 😄
