### ISSUE TITLE
[BUG] Dev tools: memo/forwardRef components names are empty in the Components tab

### ISSUE THREAD

**Issue by darkowic** [cerebral/overmind#406]
Components names are empty when component is wrapped with `React.memo` or `React.forwardRef`
```tsx
const SomeComponents = () => {
  useOvermind();
  return ...
}

export default React.memo(SomeComponents)
```

![2020-05-30_17-15](https://user-images.githubusercontent.com/11510581/83332018-2a347b80-a299-11ea-9269-85fcb6a62950.png)

**Comment by christianalfoni** [comment]
I just wish Typescript could use the variable name... but there is a lot of pushback on this for some reason. We depend on React internals to name the components and that seems to be lost here. But if you name your component with `function SomeComponent() {}` instead, I believe you are good 😄 

Please reopen if still issue

**Comment by darkowic** [comment]
@christianalfoni well then I am not sure how to define types correctly for function.

![2020-06-07_17-47](https://user-images.githubusercontent.com/11510581/83973475-ecfa6a00-a8e6-11ea-8876-e99f40eaf9fc.png)

It works for the react profiler so, I believe, it is possible and there is already a solution for it. IMHO we should reopen it and someone can take it later. I was thinking to try it in some spare time

**Comment by christianalfoni** [comment]
Hm, I have some colleagues who worked with the React Devtools integration for Codesandbox, maybe they can give a hint to where they grab that information from. Will get back to you on this 😄

**Comment by christianalfoni** [comment]
Oh, haha, but you fixed it? 😂 Closing it now, reopen if still issue
