### ISSUE TITLE
Increasing number of Symbol(CACHED_PROXY) attached to tracked object

### ISSUE THREAD

**Issue by darkowic** [cerebral/overmind#408]
_Question from discord_

Is it expected that the number of Symbol(CACHED_PROXY) increases with each call of action? See it here https://codesandbox.io/s/overmind-counter-xu0ou
![proxies_in_state](https://user-images.githubusercontent.com/11510581/83972911-347ef700-a8e3-11ea-8fcd-f703978d28b6.png)

The answer:
> Yes, in Development. Because it creates an isolated context for every action call to track it for the devtools

Add note about it somewhere in docs. Any idea where? FAQ maybe?

_I hope people will find this issue in google at least ;)_

**Comment by christianalfoni** [comment]
Thanks for pointing it out here for discoverability 😄 

Yeah, if you want to add FAQ on it that would be awesome! There is an "edit on Github" link here: https://overmindjs.org/faq
