### ISSUE TITLE
[BUG] A new derived API causes Typescript error

### ISSUE THREAD

**Issue by suevalov** [cerebral/overmind#410]
After upgrading to `overmind@24.0.0` I see the following Typescript error:

> TS2345: Argument of type '(state: State) => string' is not assignable to parameter of type '(state: IState, rootState: IState) => any'.   Types of parameters 'state' and 'state' are incompatible.     Type 'IState' is missing the following properties from type 'State': defaultLocaleCode, list

* Typescript version: 3.9.5
* Overmind version: 24.0.0

1. I use explicit typing:

```javascript
declare module 'overmind' {
  interface Config
    extends IConfig<{
      state: typeof state;
      actions: typeof actions;
      effects: typeof effects;
    }> {}
}
```

2. Code to reproduce the error:

```javascript
import { derived } from 'overmind';
import { Locale } from 'core/typings';

export type State = {
  defaultLocaleCode: string;
  list: Locale[];
};

export const state: State = {
  defaultLocaleCode: derived((state: State) => { // <------- here typescript complains
    return state.list.find((locale) => locale.default === true)?.code ?? 'en-US';
  }),
  list: [],
};
```

**Comment by christianalfoni** [comment]
Hi @suevalov ,

That is super weird. Cause `State` does extend `IState`... hm, what is your tsconfig?

**Comment by suevalov** [comment]
@christianalfoni 

here it is:

```
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
```

I was able to reproduce the same error in two projects actually, with different TS settings.

**Comment by christianalfoni** [comment]
Thanks!

Very weird, worked just fine ad Codesandbox, hm. And we also use explicit typing. 

But will set up a basic example now and test 😄

**Comment by christianalfoni** [comment]
Btw, I see some really weird behaviour from Typescript related to folders here. It treats these two imports as imports from the folder overmind:

```ts
import { createOvermind } from 'overmind'
import { config } from './overmind'
```

Will update docs on this, though just wanted to mention it for now, looking at issue now 😄

**Comment by christianalfoni** [comment]
Ah, okay, it is `strict` mode. Let me see what we can do here.

**Comment by christianalfoni** [comment]
Okay, so pushed a fix to `next` where this typing is fixed.

If you want to use it, make sure you install all overmind packages with the `@next` tag.

When this one is ready, it is available: https://travis-ci.org/github/cerebral/overmind/builds/696549177

**Comment by suevalov** [comment]
@christianalfoni just check it out and it fixes the issue 🎉 

huge thanks as usual 💯
