### ISSUE TITLE
[BUG/QUESTION] 'get' and 'set' accessors cannot declare 'this' parameters.

### ISSUE THREAD

**Issue by danawoodman** [cerebral/overmind#415]
The docs [here](https://overmindjs.org/core/typescript#getter) say to do the following:

```ts
export const state: State = {
  foo: 'bar',
  get shoutedFoo(this: State) {
    return this.foo + '!!!'
  }
}
```

If I do that, I get the following error:

```
'get' and 'set' accessors cannot declare 'this' parameters.
```

I assume this might be related to my TS config, but I'm unclear (based on searching), what to do about it. Any suggestions or is this indeed an issue?

**Comment by geirsagberg** [comment]
Yeah noticed this too. However, as far as I can tell, you don't really need to specify the `this` parameter, you can still use `this` in the getter body and get correct typings.

**Comment by christianalfoni** [comment]
Yeah, this is probably old TypeScript stuff, removed it from docs 😄
