### ISSUE TITLE
Using only namespaced, typing does not work

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/overmind#417]
This does not work `const config = namespaced({ ... })`

**Comment by Relatora** [comment]
Hi, I'm new to Typescript but as you say in one of your videos using overmind helps. I spent a lot of time checking (https://overmindjs.org) structuring the app in Typescript using multiple namespaces with no success. I'm unable to use the context successfully in actions under a specific namespace. Also if I use merge what will the overmind\state.ts file look like. If you can help me in anyway, I'll really appreciate it.

**Comment by corlaez** [comment]
@Relatora there is a discord you can join and try asking there https://discord.com/invite/CdpmRhQ

**Comment by christianalfoni** [comment]
Not able to reproduce this anymore, hm 🤔
