### ISSUE TITLE
It is possible to type actions in Overmind with plain functions, document it

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/overmind#418]
```ts
import { Context } from 'overmind'

export function myAction(context: Context, value: void) {

}
```

**Comment by brasilikum** [comment]
I think this is great. Do you see any downsides to making this de default in the future?
In my opinion reducing the number of new concepts people have to learn is important and this is just good old ts.

**Comment by amrdraz** [comment]
I wonder if the switch to this approach is what triggered #429

**Comment by christianalfoni** [comment]
Hi there and sorry for an extremely late answer! 

Yeah, it does make sense. When working on the typed API of Overmind there was a huge question of where the typing should happen. I see now that we might have taken a wrong turn on forcing "left side typing". 

I will definitely document this for next release, noting it as equally correct way of doing the typing 😄 

In next version I am also fixing so that you do not have to explicitly set `value: void` , can drop that 😄

**Comment by christianalfoni** [comment]
Thinking about this... we should make this default, it certainly simplifies!

**Comment by christianalfoni** [comment]
Released
