### ISSUE TITLE
[BUG] Proxy breaks ES6 Maps and Sets

### ISSUE THREAD

**Issue by rghamilton3** [cerebral/overmind#419]
I think this is related to #367. Attempting to call a function for a map or set stored in state results in
```
TypeError: Method Set.prototype.entries called on incompatible receiver [object Object]
    at Proxy.entries (<anonymous>)
    at Proxy.func.func (Proxyfier.js:248)
```

I've confirmed that the same map and set work if they're not in state.

**Comment by christianalfoni** [comment]
This should be fixed in next release, https://github.com/cerebral/overmind/commit/4e6f4248f552e77775a48ca3177e388a4c9999f6
