### ISSUE TITLE
[QUESTION] How to instantiate many state machines of same type

### ISSUE THREAD

**Issue by M0dM** [cerebral/overmind#420]
Hi,

I am trying to design a parallel file upload state machine.
What I would like to achieve this is to use inside this uploadMachine sub-machines (One for each file) available inside the uploadMachine state.

The goal is to avoid this kind of dirty code: 
```typescript
const files: File[] = [];
const successfullyUploadedFiles: boolean[] = [];
const failedFiles: boolean[] = [];

// with many derived to find in which state the global "machine" is
```

And instead use something like this:
```typescript
const fileUploadMachine = statemachine(
    {
        DROPPED: ['UPLOADING'],
        UPLOADING: ['OK_OR_GIVUP', 'FAILED'],
        FAILED: ['RETRYING'],
        RETRYING: ['UPLOADING', 'OK_OR_GIVUP']
    }, {
        state: 'DROPPED',
        file: null,
        maxRetry: 2
  }
)

const uploadMachine = statemachine(
    {
        EMPTY: ['UPLOADING'],
        UPLOADING: ['DONE']
    }, {
        state: 'EMPTY',
        fileMachines: []  // A list of fileUploadMachine
    }
)
```

As the statemachine documentation is still sparse,
I would like to know if anyone could help me on the subject.

Am I thinking wrong ?
Is there another better way to do such thing ?

M0dM

**Comment by christianalfoni** [comment]
The last iteration of state machines allows you to do this, let me know if there is still any confusion around this: https://overmindjs.org/guides-1/using-state-machines#instantiating-a-machine

**Comment by M0dM** [comment]
Unfortunately, I will not have time to develop some frontend until a couple of month.
Nevertheless, it seems awesome, thanks a lot.
