### ISSUE TITLE
[BUG] Unable to start VS Code devtools

### ISSUE THREAD

**Issue by arahansen** [cerebral/overmind#421]
I'm seeing the following console error in VS Code when attempting to start the devtools after following the installation instructions

![image](https://user-images.githubusercontent.com/8746094/86314214-f2905a80-bbdb-11ea-94f9-ac9f1894b0d9.png)

**Comment by eirikhm** [comment]
Which version of VSCode are you using?

**Comment by christianalfoni** [comment]
Closing for now, please reopen if still issue. you can also run standalone: `npx overmind-devtools@latest`
