### ISSUE TITLE
[BUG] 🚨 Can't find variable: location 🚨 in Expo starting v24 

### ISSUE THREAD

**Issue by tommycodebox** [cerebral/overmind#422]
## 🧠 Description
Starting `overmind@24.0.0` when initializing with `createOvermind(config)` in Expo React Native application, it crashes with error below

Although `overmind@23.1.0` is working completely fine

## 🚨 Error
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-03 at 22 11 21](https://user-images.githubusercontent.com/52791021/86493585-bc3d1180-bd7a-11ea-8505-f2dd88146ff0.png)

**Comment by humarh-dharnarh** [comment]
I was also having this reference error bug on expo but since I updated to overmind@25.0.1, it works perfectly.

**Comment by brasilikum** [comment]
Same here. Fixed with 25.0.1
