### ISSUE TITLE
Subscriptions / WebSocket Issues

### ISSUE THREAD

**Issue by zyonnetworks** [cerebral/overmind#426]
Hi there!

I've been having issues connecting to web socket for subscriptions.  Could you please help? I keep getting this issue:

`WebSocket connection to 'wss://domain.com/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400`

Is this a CORS/NGINX issue? Do I have to configure anything special in Overmind init?

Please advise.

**Comment by edgesoft** [comment]
@zyonnetworks Is this still the case? We connect using Overmind and Golang backend. This is nothing overmind specific. If the error remains can you please post your settings so that we can have a look?

**Comment by christianalfoni** [comment]
We are not using anything to the underlying library `@absinthe/socket`, so should not be Overmind specific. Please reopen if it is 😄
