### ISSUE TITLE
[BUG] Class-based state "TypeError: mutationTree.addMutation is not a function" error

### ISSUE THREAD

**Issue by danawoodman** [cerebral/overmind#427]
*Posted this in Discord but saw no response, so cross posting here*

I'm getting a `TypeError: mutationTree.addMutation is not a function` error when trying to do some tests on a Class-based state. The state is super simple:

```ts
export class MyModel {
  something = ""

  setSomething(something: string): void {
    this.something = something
  }
}
```

My state.ts:

```ts
export const state: State = {
  myModel: new MyModel(),
}
```

Then in my test I'm doing:

```ts
const store = createOvermindMock(config)
const {
  state: {
    myModel,
  },
} = store
myModel.setSomething("hello")
```

The tests are throwing. Is there something I'm missing? Using latest overmind w/ Jest and Typescript.  Note: I've excluded unrelated code for brevity)

Thanks for any guidance!

**Comment by christianalfoni** [comment]
Hi there!

It is not this you are seeing?

<img width="535" alt="Screenshot 2021-01-09 at 15 12 20" src="https://user-images.githubusercontent.com/3956929/104093789-1ae4ca00-528d-11eb-9e4c-c9dc8e2ddfac.png">

Cause you can not mutate state directly, you have to do it through an action.

Please reopen if anything is unclear... and very sorry for late response here, but had a baby and been out of the game for a few months 😄

**Comment by christianalfoni** [comment]
Hi there, I saw I already had an issue for follow up: https://github.com/cerebral/overmind/issues/431

Next version will make this easier to deal with
