### ISSUE TITLE
[BUG] Rehydrate state from storage removes derived boolean.

### ISSUE THREAD

**Issue by HeroBanana** [cerebral/overmind#437]
Hi,

The documentation mention that it is possible to rehydrate the state https://overmindjs.org/api-1/rehydrate. But the problem is when you use for example the derived function and start to rehydrate the state. This state contains a boolean and overrides the derived function, I think. I guess it is a bug?

```tsx
// Use of the derived function
export const state: State = {
    /** User object. */
    token: null,
    /** Determine user logged in. */
    isLoggedIn: derived((state: State) => Boolean(state.token !== null)),
}
```

```tsx
export const onInitialize: OnInitialize = async ({effects, state}) => {
    // Get state from storage.
    const previousState = await effects.storage.getItem('@store/state');

    // Rehydrate Overmind state.
    if (previousState !== null) {
        rehydrate(state, JSON.parse(previousState));
    }
}
```

**Comment by brasilikum** [comment]
@HeroBanana how are you saving the state?

**Comment by christianalfoni** [comment]
Derived state should be ignored when rehydrating, is this still an issue?

**Comment by christianalfoni** [comment]
Not able to reproduce this, works here: https://codesandbox.io/s/sharp-field-v62bi?file=/src/index.js. Maybe fixed already?
