### ISSUE TITLE
[BUG] merge cannot work with only onInitialize

### ISSUE THREAD

**Issue by nireak** [cerebral/overmind#439]
Hello,

If I write my overming config js like this
```js
import { onInitialize } from './onInitialize'
import * as ui from './ui'

export const config = merge(
  {
    onInitialize
  },
  namespaced({
    ui
  })
)
```
I get the error: "TypeError: Cannot read property 'ui' of undefined" at merge.ts:12

But If I add a root state
```js
import { onInitialize } from './onInitialize'
import { state } from './state'
import * as ui from './ui'

export const config = merge(
  {
    onInitialize,
    state
  },
  namespaced({
    ui
  })
)
```
then it works fine.

Am I missing something?

Thank you

**Comment by grandevel** [comment]
Confirm I had the same thing, worked fine in v24. In an attempt to bypass it I moved onInitialize to the namespace and removed the merge, which resolved that issue, but have had to go back to v24 anyway due to some strange issue with illegal invocations in v25 (unrelated).

**Comment by christianalfoni** [comment]
Oh, interesting, let me fix this for next release!

**Comment by christianalfoni** [comment]
Okay, fixed in `next`, ready for next release

**Comment by christianalfoni** [comment]
Released
