### ISSUE TITLE
Make State Getters Automatically Derived

### ISSUE THREAD

**Issue by doc987** [cerebral/overmind#450]
Is it possible/sensible to make it so that ```get``` functions in the state are automatically derived, thereby avoiding the need to wrap every derived item in a ```derived``` function call?

**Comment by brasilikum** [comment]
@doc987 correct me if I am wrong, but getters and derived are explicitly different:
- derived update immediately and are behaving more like a state

**Comment by christianalfoni** [comment]
@doc987 @brasilikum We actually made plain functions automatically become derived, but this was changed later on to explicitly use `derived`. The reason being typing. Typing would also be an issue for a `getter` actually being a derived. Also you would not be able to access the `rootState` from a getter. Last, but not least, derived does add an overhead. When using a `getter` you really just want a native JavaScript `getter` with no overhead. Derived should really be used when there is some expensive computation or you need to access the `rootState` or other state not immediately available. Other than that you can just use a plain `getter` which has the least overhead 😄
