### ISSUE TITLE
[BUG] memory leak caused by overmind during SSR when using createOvermindSSR

### ISSUE THREAD

**Issue by SergeiKalachev** [cerebral/overmind#451]
**UPDATE 29 September 2020:** 
We have discovered a memory leak.

On our server we use nodejs + express + server side rendering with overmind.
During SSR we have several functions `initialize`, each one calls 1-3 `effects.gql.queries.someGQLAction`.
Example: 
```javascript
export const initialize = withCatchDuringInitializeSSR(
  async ({ state, effects }: SSRConfig) => {
    const productsResponse = await effects.gql.queries.getProducts()

    const products = overmindNormalize(
      productsResponse.products,
      "id"
    );
    state.comet.products.data = products;
  },
  "comet"
);
```
This effect is based on [Overmind graphql addon](https://overmindjs.org/addons/graphql)

Once we deployed the code we noticed memory leaks reflected in our memory charts:

![Screen Shot 2020-09-28 at 3 55 20 PM](https://user-images.githubusercontent.com/35598345/94442626-78ed1600-01a4-11eb-8e67-6c5df77e9146.png)

investigating with the help of [heap profiler](https://github.com/v8/sampling-heap-profiler) over consecutive snapshots we noticed that memory is held by one function:

<img width="1119" alt="Screen Shot 2020-09-28 at 1 19 41 PM" src="https://user-images.githubusercontent.com/35598345/94444580-c2d6fb80-01a6-11eb-9d8e-c8c77d7d6fdc.png">

it seems this function is the source of the leak. We don't know exactly why. Here is the stack:
1) our initialize.ts function with effect call
2) overmind-graphql internals
3) `graphql-request/src/index.ts --> GraphQLClient.prototype.request`
4) `graphql-request/node-modules/node-fetch/lib/index.js` json()

json() looks like:
```javascript
    json() {
      var _this2 = this;
      return consumeBody.call(this).then(function (buffer) { // <--- leak is caused by this function
        try {
          return JSON.parse(buffer.toString());
        } catch (err) {
          return Body.Promise.reject(...));
        }
      });
    },
```

overmind-graphql 5.0.2 uses old version of graphql-request 1.8.2 (last 3.1.0), that in turn uses cross-fetch 2.2.2 (last 3.0.6) and cross fetch uses node-fetch 2.1.2 (last 2.6.1)
I believe if overmind-graphql updates `graphql-request` to the latest version problem can vanish.
Probably this PR https://github.com/cerebral/overmind/pull/447 can be just merged?

**UPDATE 1 October 2020:** 
We discovered the source of the leak. It is overmind itself, not the dependency.
Not sure why heap profiler shows function from node-fetch as a bottleneck, probably because objects that are held in memory are coming from this function.

![image](https://user-images.githubusercontent.com/35598345/94819143-3410eb80-03ff-11eb-9485-f81d38e4f6c4.png)

Overmind places Symbols into objects each time we render page on the server. If we supply `config` to `createOvermindSSR` it adds symbols there and since `config` is a global object it holds Symbols and Symbols hold references to objects which are not needed once rendered page sent back to client. Garbage collector can't free them up.

it also happens if let's say I have global constant:

```javascript
export const PRODUCTS = { product_1: { array_1: [] }, product_2: { array_2: [] }  }
```

and then during SSR I place it into state:

```javascript
state.products = PRODUCTS
```

then Overmind pollutes this global constant with Symbols on each server page render which leads to memory leak.

If it is still not clear @christianalfoni I will try to provide reproducible demo later once I have time.

**UPDATE 1 October 2020:** 

I created small repo with reproduction of the problem: https://github.com/SergeiKalachev/overmind-ssr-leak-demo

**Comment by christianalfoni** [comment]
Hi @SergeiKalachev and thanks a bunch for an excellent deep dive!

For the next release I will explore an SSR mode for `proxy-state-tree`. It basically will not add the symbols to the objects, but just free up the proxies as they are being created 👍

**Comment by marbemac** [comment]
@christianalfoni what are your latest thoughts on this one - any developments or change of plan?

**Comment by christianalfoni** [comment]
Hi @marbemac,

I am diving into it right now 😄

**Comment by christianalfoni** [comment]
Okay, so I have pushed a fix for this. It just does not use the `Proxifier` at all in SSR mode. It is not extensively tested, but in theory this should work 😄 

It will be in `next` shortly and you can test it by install al Overmind packages with the `@next` tag. You will see the commit on this list: https://travis-ci.org/github/cerebral/overmind/builds

**Comment by christianalfoni** [comment]
@marbemac @SergeiKalachev would you guys have a chance to test this? 😄

**Comment by SergeiKalachev** [comment]
> would you guys have a chance to test this? 😄

I will test it this week.

**Comment by christianalfoni** [comment]
Just wanted to say I made a new commit now, which explicitly drops proxy caching, but still uses proxies for the state tree. I realised that of course we still need to proxy for derived to work. So yeah, no caching on SSR is the fix 😄

**Comment by christianalfoni** [comment]
Released

**Comment by marbemac** [comment]
Awesome thanks @christianalfoni! We're a few versions back but will try to schedule an upgrade soon.

**Comment by SergeiKalachev** [comment]
@christianalfoni sorry for the late reply.
I had a chance to test it. I upgraded to the version `27.0.0` and removed my workaround for avoiding memory leak.
It seems the memory leak is no longer there:

![Screen Shot 2021-02-19 at 9 12 48 AM](https://user-images.githubusercontent.com/35598345/108477179-303d1300-7293-11eb-9cbc-7d443ffe9ea5.png)

Chart looks quite smooth. It goes slowly up but I think it will reach some point and stop at it (based on the data for previous days).
Thank you very much for the fix!

**Comment by christianalfoni** [comment]
Great! Thanks for reporting 😄
