### ISSUE TITLE
[BUG] Tracking / statehooks of built in objects, like Date, broken in versions after v21

### ISSUE THREAD

**Issue by stianeikeland** [cerebral/overmind#453]
Compare the following two identical sandboxes.

State: a single Date
Actions: a single action to update Date

[Overmind v21](https://codesandbox.io/s/vn0ty)
[Overmind v25](https://codesandbox.io/s/vsyeq)

v21 renders current unixtime when button is pressed, v25 doesn't re-render.

Overmind releases after v21 also seem to have issues with other built-ins, like Map/Set, too (as reported in #419)

**Comment by stianeikeland** [comment]
```typescript
import { ProxyStateTree } from "proxy-state-tree";

type State = { date: Date };

const tree = new ProxyStateTree<State>({ date: new Date() });
const trackStateTree = tree.getTrackStateTree();
trackStateTree.track();

console.log(trackStateTree.state.date);
console.log(Array.from(trackStateTree.pathDependencies));
```

Expected output: ["date"]
Output from proxy-state-tree v4.6.0: ["date"]
Outout from proxy-state-tree v5.0.0 or later: []

**Comment by christianalfoni** [comment]
Okay, thanks so much for a great example! This is in `@next` shortly: https://travis-ci.org/github/cerebral/overmind/builds/753660679

**Comment by christianalfoni** [comment]
Released
