### ISSUE TITLE
Is browsers tabs synchronization possible?

### ISSUE THREAD

**Issue by frederikhors** [cerebral/overmind#456]
Hi guys! Thanks for this amazing project!

I recently discovered Overmind and today I would like to start using it, but I don't understand from the docs site if synchronization between multiple browser tabs is possible.

Yes or no?

**Comment by eirikhm** [comment]
As far as I know there is no support for this out-of-the-box in Overmind. This should be solvable with [BroadcastChannel](https://developers.google.com/web/updates/2016/09/broadcastchannel). 

By using `addMutationListener` or `addFlushListener` you can listen for state change which then can be sent via BroadcastChannel.postMessage. It's not supported in Safari, so IndexedDB or LocalStorage could be a viable fallbacks. [pubkey/broadcast-channel](https://github.com/pubkey/broadcast-channel) looks like a good candidate.

In `OnInitialize` you'd set up an effect which wraps ´BoardcastChannel.onmessage´ and calls an action that applies the state changes. See #195 for more information. @christianalfoni can perhaps give some additional pointers on how to apply the changes.

**Comment by christianalfoni** [comment]
Hi there 😄 

I am curious why you want to drive state sync directly between tabs? Opposed to the server sending messages on data updates? 

But yeah, I would listen to all mutation and pass them over a channel where the mutation is rerun. You can read about rehydration of mutations related to server side rendering: https://overmindjs.org/core/server-side-rendering#rehydrate-on-the-client 😄

**Comment by christianalfoni** [comment]
Closing this for now, please reopen if more questions 😄
