### ISSUE TITLE
How to persist state in browser?

### ISSUE THREAD

**Issue by frederikhors** [cerebral/overmind#457]
Hi guys! Thanks for this amazing project!

I would like to know if is possible to persist state in LocalStorage or (better) IndexedDB between user sessions to speed up data visualization using something like Apollo `networkPolicy: cache-and-network`.

Yes or no?

**Comment by eirikhm** [comment]
Hi @frederikhors!

As I touched on in #456 you'd use `addMutationListener` to keep track of changes to the state. You can then either persist the whole state to LocalStorage, or certain parts.

When doing a full page load, fetch the state from LocalStorage and assign it to state inside OnInitialize :-)

**Comment by frederikhors** [comment]
Ok. I'm new to this. Is there an example?

**Comment by eirikhm** [comment]
@frederikhors Seems like `reactions` is the way to go actually. Have not used those, but seems pretty straight-forward. See a fully working sample at  https://codesandbox.io/s/overmind-todomvc-typescript-vlulp?file=/src/app/onInitialize.ts. It's running an older version of Overmind, but the relenant bits should still be valid. The docs also mention this: https://overmindjs.org/api-1/reaction

**Comment by christianalfoni** [comment]
Closing this for now, but please reopen if you are stuck @frederikhors or join us on discord 😄  (Link on website)
