### ISSUE TITLE
[BUG] graphql subscription in electronjs app

### ISSUE THREAD

**Issue by RyszardRzepa** [cerebral/overmind#462]
I am using overmind in electronjs app. 
When using subscription I am getting this error:

`phoenix.js:1 WebSocket connection to 'ws://micurai-dev.herokuapp.com/v1/graphql/websocket?vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 404`

Is this error related to the overmind, phoenix or websockets in general? 

My overmind init function:  

```
const onInitialize: OnInitialize = ({ state, effects }) => {
  effects.gql.initialize({
    endpoint: 'https' + DB_URL,
    // This runs on every http request
    headers: () => ({
      authorization: `Bearer ${state.auth.authToken}`
    }),
  }, {
    endpoint: 'ws' + DB_URL,
    // This websocket runs on every connect
    params: () => ({
      token: state.auth.authToken
    })
  })
}
```

**Comment by christianalfoni** [comment]
@RyszardRzepa Hi there!

We are not doing anything to the web socket, we are directly using the `@absinthe/socket` and `phoenix` library, so I would check there 😄 

Please reopen if still suspecting Overmind

**Comment by yovanoc** [comment]
There is still an issue with this, apparently phoenix add /websocket to the url by default, so we have no solution overmind side
