### ISSUE TITLE
[BUG] Not working with svelte

### ISSUE THREAD

**Issue by floratmin** [cerebral/overmind#463]
When setting fresh project up with `npx degit sveltejs/template overmind` and then installing `overmind` and `overmind-svelte` and following the tutorial on `https://overmindjs.org/views/svelte` i get the following error on the command line:

```
(!) Circular dependency
node_modules/overmind/es/utils.js -> node_modules/overmind/es/statemachine.js -> node_modules/overmind/es/utils.js
```
And the following error in dev tools when trying to open the page:
```
Uncaught ReferenceError: process is not defined
    at utils.js:4
    at main.js:8
```

**Comment by christianalfoni** [comment]
@floratmin That circular dependency is not a real issue, but I can get that fixed 😄 

The missing `process` seems to be Rollup issue, which is the build tool Svelte uses. I have seen the same in other build tools. Libraries use `process` to determine the environment it is running in and most build tools expose this by default. Does not seem that Svelte does this? You see the same here: https://github.com/davidkpiano/xstate/issues/443

This seems to be the solution: https://www.npmjs.com/package/rollup-plugin-inject-process-env

I will add this to the docs.

**Comment by abalmos** [comment]
For what it is worth, svelte does not require or use rollup. Svelte's default templates often do, but snowpack is emerging as an alternative choice. Svelte kit will depend on snowpack.

**Comment by christianalfoni** [comment]
I have a fix for `process` in `next` now, will fix circular typing to avoid warning there as well

**Comment by christianalfoni** [comment]
Released

**Comment by bjorntheart** [comment]
@abalmos Actually, no, Sveltekit uses Vite. Snowpack was dropped https://twitter.com/SvelteSociety/status/1368611725105238018?s=20

**Comment by abalmos** [comment]
@bjorntheart Actually, no, that was not true at the time. SvelteKit was well understood to be using Snowpack (Rich Harris said it while announcing SevlteKit at Svelte Summit 2020, https://svelte.dev/blog/whats-the-deal-with-sveltekit). Sure, he moved SvelteKit to Vite before its first public release, but that was in March, well past the lifespan of this issue.

Anyway, the topic here is Svelte, not SvelteKit. I was merely pointing out that Svelte does not use roll up. In fact, it doesn't use _anything_. It was true and _still is_ true that this particular error can be avoided by selecting Snowpack over rollup for your project--which at the time _was_ the clear future of the Svelte community from Harris' own mouth.

All that said, I don't understand your point @bjorntheart. Is there something this old and closed issue needs to reconsider?
