### ISSUE TITLE
Using with JSON:API?

### ISSUE THREAD

**Issue by frederikhors** [cerebral/overmind#465]
I am exploring the territory to understand whether to use [JSON: API] (https://jsonapi.org).

Can I use Overmind for this?

**Comment by christianalfoni** [comment]
Hi @frederikhors ,

I do not see any reason why not? Looking at this it is more of a server implementation and how you consume JSON when it is received from the server. Overmind does not really care about that, it is still just JSON 😄 

Please reopen if I misunderstood something.
