### ISSUE TITLE
[BUG] Async actions in server side removes previous mutations.

### ISSUE THREAD

**Issue by ksmsk** [cerebral/overmind#466]
Title might be confusing i try to eloborate. Using async actions in server side causes `hydrate()` to ignore any previous actions and to hydrate only the last async action you called. I made a minimal repo for this issue.

https://github.com/ksmsk/overmind-async-action-bug

**Comment by christianalfoni** [comment]
Okay, a fix for this should now be in `next` 😄

**Comment by christianalfoni** [comment]
Released! 🎉
