### ISSUE TITLE
The overmind-vue plugin uses the deprecated "beforeDestroy" lifecycle hook

### ISSUE THREAD

**Issue by d-bardiau** [cerebral/overmind#467]
The overmind-vue plugin uses the old "beforeDestroy" interface to hook in. Within Vue 3 the interface is renamed to "beforeUnmount" and Vue warns about it: 

![image](https://user-images.githubusercontent.com/17627755/100070934-cb605100-2e3a-11eb-80b6-d196b97cb7fb.png)

This might be the affected line:

https://github.com/cerebral/overmind/blob/626b83acb8958cc426b2f8ba7ba711f52cf189ef/packages/node_modules/overmind-vue/src/index.ts#L118

**Comment by christianalfoni** [comment]
In next release I will split up the imports for Vue2 and Vue3, also update Vue3 to comply with the official release 😄

**Comment by christianalfoni** [comment]
Now in `next` you can import Vue 3 specific stuff from `overmind-vue/vue3`

**Comment by christianalfoni** [comment]
Released
