### ISSUE TITLE
[BUG] HMR breaks on simple case, misuse or bug?

### ISSUE THREAD

**Issue by nahuel** [cerebral/overmind#468]
HMR+Overmind-react stops working after changing a top level module variable. To reproduce do the following:

```sh
npx create-react-app test1 --use-npm
cd test1
npm install overmind overmind-react
```

Then on `test1/src` replace the `index.js` and `App.js` files with the following versions, also add `state.js`:

```js
///---- index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { Provider } from 'overmind-react'
import { createOvermind } from 'overmind'
import { config } from './state'

const overmind = createOvermind(config)

ReactDOM.render(
  <Provider value={overmind}>
    <App />
  </Provider>,
  document.getElementById('root')
);

if (module.hot) {
  console.log('HMR accept()');
  module.hot.accept()
}


///---- App.js
import { useState, useActions } from './state'

export const a = 1

function App() {
  const state = useState()
  const actions = useActions()

  return (
      <div>
          <button onClick={() => actions.setTitle(Math.random())}>
            setTitle {a}
          </button> 
          {state.title} 
    </div>
  );
}

export default App;


///---- state.js
import {
    createStateHook,
    createActionsHook
} from 'overmind-react'

const state = {
  title: 'initial'
}

const setTitle  = ({ state }, title : string) => {
  console.log('setTitle', title)
  state.title = title
};

export const config = {
  state,
  actions : { setTitle }
}

export const useState = createStateHook()
export const useActions = createActionsHook()
```

Now run `npm start`, then do the following:

1. Press the `[setTitle 1]` button many times, is working ok.
2. Change the `App.js` `export const a = 1` line to `export const a = 2` and save.
3. The module reloads ok, now press the `[setTitle 2]` button, is working, you can repeat the step 2,3 many times and it never brokes.
4. Change the line to `const a = 3` (without the `export` clause) and save.
5. The module reloads ok, now press the `[setTitle 3]` button, works ok.
6. Change the line to `const a = 4` and save.
7. The module seems to reload ok, the button shows as `[setTitle 4]`, BUT if you press it, the random number is not refreshed on the component (but the action is dispatched, as you can see in the console)
8. Repeat the step 6, is the same, the `[setTitle X]` button label will be refreshed, but will be still broken.

Note, if you began these steps with `const a = 1` (no initial `export` clause), then the first reload will break the app. I added the `export` clause to show the difference in behavior.

**Comment by christianalfoni** [comment]
Hi @nahuel ,

I am not sure if this is an Overmind issue? There are many situations HMR does not work related to side effects and you need to refresh anyways. Especially side effects unrelated to the framework that supports it.

So when you change stuff inside components React deals with HMR and if you change stuff inside actions/state etc. Overmind deals with it. But you are changing stuff "in between" these two worlds. I would not expect that to work.

Diving into this would require a lot of research and I am a bit reluctant to spent time on it, as it seems like an edge case Overmind can not really do anything about. 

Please let me know if you think I am wrong here and reopen the issue, but will close it for now 😄
