### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by lukaszraczylo** [cerebral/overmind#469]
**Idea:** Author of the project is visibly too busy with the other tasks ( like codesandbox ), therefore it would be nice if he'd designate maintainers to not allow such an amazing project to die.

**Update ( in the spirit of fairness and openness )**: Author of the project have a reasonable excuse to be busy, and on this note I'd like to congratulate him on the new member of the family ❤️

**Comment by christianalfoni** [comment]
Haha, thanks @lukaszraczylo. It was just a really bad move of me to not notify about this early on, but I was desperately moving into "bubble mode" and opening Discord/Github would have made me feel so bad, even to just say I will be away for a couple of months. 

But yeah, I am back now and continuing the work 😄 ❤️

**Comment by jadbox** [comment]
@grandevel It is now 08/2022 and there hasn't been an update in some time. Is there any plan to maintenance?
