### ISSUE TITLE
[BUG] Action using pipe does not return the last value

### ISSUE THREAD

**Issue by Michielnuyts** [cerebral/overmind#471]
The pipe should return the value returned from the last operator in that pipe.
Currently it always returns undefined.

I reproduced it in 2 examples, with logging added.

Reproduced here: https://codesandbox.io/s/loving-fog-kp8rj?file=/src/App.js

**Comment by christianalfoni** [comment]
Hm, let me look into this 😄

**Comment by christianalfoni** [comment]
This works on the `next` release 😄 A few operators has been removed in favour of action interoperability, but here you see it running: https://codesandbox.io/s/practical-matsumoto-2ghb8?file=/src/overmind/actions.js

**Comment by Michielnuyts** [comment]
> This works on the `next` release 😄 A few operators has been removed in favour of action interoperability, but here you see it running: https://codesandbox.io/s/practical-matsumoto-2ghb8?file=/src/overmind/actions.js

Thanks!

**Comment by christianalfoni** [comment]
Released! 🎉
