### ISSUE TITLE
store.subscibe is not a function

### ISSUE THREAD

**Issue by joshua1** [cerebral/overmind#482]
I get the error 
```
Unhandled Runtime Error
Uncaught TypeError: store.subscribe is not a function
```
when using the next version and a svelte app with svelte version 3.31.* . The svelte version in overmind-svelte is 3.20 . Any chance svelte can be made a peer dependency  of overmind-svelte. i am assuming that will help.

This happens when i call a property of state as shown below 

```
$: isLoggedIn = $state.auth.isLoggedIn
```

**Comment by joshua1** [comment]
Seems like this issue is not detailed enough #483

**Comment by abalmos** [comment]
@joshua1 This is actually a bug in the Sevlte integration. I have a fix, but I have not had time to package it up.
