### ISSUE TITLE
[BUG] source code contained in folder named node_modules can't be found by github search

### ISSUE THREAD

**Issue by Jwhiles** [cerebral/overmind#484]
Whilst trying to understand some aspects of this project I observed that github's code search fails to find any of the source code. I suspect this is because the packages are in a subfolder named `node_modules`, which I assume will be automatically filtered out of the results. It actually took me quite a while to find where the source code was located as I'm conditioned to think that a folder named node_modules will contain dependencies.

![image](https://user-images.githubusercontent.com/20307225/105363160-07761f00-5bfc-11eb-80e6-e8fb4fd42c70.png)

I suspect that this naming could also cause code search problems in some development environments. 

Obviously not a huge issue, but I wanted to make you aware of the potential for confusion.

**Comment by christianalfoni** [comment]
Hi @Jwhiles and thanks for the heads up!

All the way back with Cerebral there were no good tools to do monorepos, so we built our own. This was also used for `overmind`. There was a lot of back and forth on using `node_modules` as folder name, but it was chosen to simplify linking packages. 

This is certainly a drawback, but it would be way too much work to rip it out now 😄
