### ISSUE TITLE
[BUG] Graphql queries and mutations don't include headers in responses

### ISSUE THREAD

**Issue by RustyDev** [cerebral/overmind#487]
It would be a nice to have the option to get the full response back from graphql queries and mutations instead of `response.data`.

overmind-graphql is currently using [request](https://github.com/prisma-labs/graphql-request/blob/a8d99f5cdbe57786ecb8d99c88175599608d2fc6/src/index.ts#L81)

Would it be possible to add an option to get full response back from graphql queries and mutations using [rawRequest](https://github.com/prisma-labs/graphql-request/blob/a8d99f5cdbe57786ecb8d99c88175599608d2fc6/src/index.ts#L44)?

**Comment by christianalfoni** [comment]
Hi there!

I did a few iterations on this and ended up with extending:

```ts
const gql = graphql({
  queries: {},
  mutations: {},
  subscriptions: {},
  // NEW
  rawQueries: {},
  rawMutations: {}
})
```

This gives the most flexibility and typing is handled very straight forward. It is now in `next` which is a breaking release, but love for you to test it 😄

**Comment by RustyDev** [comment]
Thank you, trying it out now and will report back

**Comment by christianalfoni** [comment]
Released! 🎉
