### ISSUE TITLE
[BUG] overmind-statechart throws error when react fash refresh kicks in

### ISSUE THREAD

**Issue by schiller-manuel** [cerebral/overmind#492]
React's fast refresh reruns statechart when a module that contains this call is edited.
As the statechart is already initialized, a config error is thrown since states and matches are already present in the current state.

These are the affected lines:

```
 if (config.state && (config.state as any).states) {
    throw new Error(
      `Overmind statecharts: You have already defined the state "states" in your configuration. Statecharts needs this, please rename it`
    )
  }

  if (config.state && (config.state as any).matches) {
    throw new Error(
      `Overmind statecharts: You have already defined the state "matches" in your configuration. Statecharts needs this, please rename it`
    )
  }
```

starts at:
https://github.com/cerebral/overmind/blob/next/packages/node_modules/overmind-statechart/src/index.ts#L275

**Comment by christianalfoni** [comment]
Released! 🎉
