### ISSUE TITLE
overmind.hydrate() does not return anything

### ISSUE THREAD

**Issue by agritheory** [cerebral/overmind#497]
[This reproduction](https://codesandbox.io/s/currying-waterfall-9k0vf?file=/overmind/overmind.js) may be easier to understand than a description of the issue. 

Calling `overmind.hydrate()` on the server (Nuxt) does not return the serialized mutations to state as expected. Christian seems to think it might [be related to events not registering](https://discord.com/channels/133707918859173890/458548758523674645/814236957558308905) or something specific to the Nuxt environment.

**Comment by christianalfoni** [comment]
Okay, this is insanely weird. In the `Nuxt` environment, this resolves to `false`:

```ts
Object.getPrototypeOf({}) === Object.prototype
```

If you run this on Node it resolves to `true`, and it should. This is also the case for the browser. Like... `{}` IS the base object of JS. I have no idea what `Nuxt` is doing to mess this up.

Maybe Babel is doing something crazy?

**Comment by christianalfoni** [comment]
Even weirder... this ONLY happens in the `overmind.js` file, not in the middleware or plugin

**Comment by christianalfoni** [comment]
Okay, when I removed `merge` from the `overmind.js` file it suddenly got correct prototypes, but that problem continues to happen in the `overmind.plugin.js` file

**Comment by christianalfoni** [comment]
Okay, I am super confused... suddenly it starts logging out the right thing, but as I move logging into the Overmind library (in node_modules) it starts failing again. So logging:

```ts
console.log("WTF NUXT????", Object.getPrototypeOf(config.state) === Object.prototype);
```

From app code works, but when I log the exact same thing inside `node_modules` and `createOvermindSSR` function, it logs `false` for the same thing

**Comment by christianalfoni** [comment]
<img width="900" alt="Screenshot 2021-02-28 at 09 28 00" src="https://user-images.githubusercontent.com/3956929/109412272-4ccdff00-79a7-11eb-9ccc-dbe4b6cd8f9d.png">

<img width="885" alt="Screenshot 2021-02-28 at 09 28 13" src="https://user-images.githubusercontent.com/3956929/109412278-50618600-79a7-11eb-8425-44961334958e.png">

First one resolves to `true`, the other to `false` ... this is just insane?

**Comment by christianalfoni** [comment]
I could do a different check for `is_plain_obj`, but it bugs the hell out of me why this happens, it makes absolutely no sense... and it only happens in Nuxt environment...

**Comment by christianalfoni** [comment]
I did some more digging and found a couple of environment issues as well. But yeah, I have no idea why suddenly the Object prototype fails inside the Overmind package. It is insanely weird. Anyways, will fix this 😄

**Comment by christianalfoni** [comment]
Okay, I pushed a fix now, will test it when CI has done its job 😄

**Comment by agritheory** [comment]
@christianalfoni In the reproduction case above, I updated the Overmind branch to 'next' and it's hanging the browser in both Firefox and Brave.

**Comment by christianalfoni** [comment]
You have to update both packages 😄 here it is running: https://codesandbox.io/s/confident-wu-tiyv0

**Comment by agritheory** [comment]
Awesome, thank you!

**Comment by christianalfoni** [comment]
Released! 🎉
