### ISSUE TITLE
derive not returning correct derived state

### ISSUE THREAD

**Issue by gitnix** [cerebral/overmind#88]
Following along with the youtube raw preview and the guide on the website (react/typescript), I am fetching data in componentDidMount that then sets posts (`this.props.app.actions.loadPosts()`). When I add in derived state for unreadCount, the correct count appears only after I click a post to toggle it read.

I apologize if I am misunderstanding something.
Thank you for your work. :)

**Comment by gitnix** [comment]
So this is what I had
```
export const unreadCount: Derive<number> = state => {
        return state.posts.length - state.readPostIds.length
}
```

If I change it to this, then it works
```
export const unreadCount: Derive<number> = state => {
	if (!state.isLoadingPosts)
		return state.posts.length - state.readPostIds.length
	return state.posts.length
}
```

I was wondering why the first approach does not work, as mutate set posts seems to be called correctly in the debugger.

**Comment by christianalfoni** [comment]
Closing old issue
